### ISSUE TITLE
scrypt support

### ISSUE THREAD

**Issue by fbender** [bitwiseshiftleft/sjcl#122]
From http://www.tarsnap.com/scrypt.html:
<blockquote>
<p>The scrypt key derivation function was originally developed for use in the Tarsnap online backup system and is designed to be far more secure against hardware brute-force attacks than alternative functions such as PBKDF2 or bcrypt. </p>

<p>We estimate that on modern (2009) hardware, if 5 seconds are spent computing a derived key, the cost of a hardware brute-force attack against scrypt is roughly 4000 times greater than the cost of a similar attack against bcrypt (to find the same password), and 20000 times greater than a similar attack against PBKDF2. </p>
</blockquote>

`scrypt` is designed to require either an excessive amount of memory, or increase computations when using less memory. I believe it would be a nice addition to the SJCL suite.

**Comment by kaizhu256** [comment]
should this be closed since core/scrypt.js has been added?

**Comment by Nilos** [comment]
Yes, thanks for pointing it out!
