### ISSUE TITLE
ECC Questions

### ISSUE THREAD

**Issue by jpillora** [bitwiseshiftleft/sjcl#134]
I'm looking into ECC since I'm after speed and low-storage. As I understand, ECC 160bit has equivalent security to RSA 1024bit?

I'm currently writing a networking protocol (on layer 2) and I'd like each adjacent node to negotiate a public and then use them to encrypt (or sign - since I'm only after integrity).

Would there be some code examples somewhere that demonstrates using SJCL's ECC to generate public/private keys for alice and bob and encrypt-decrypt/sign-verify data?

Thanks!

**Comment by valmack** [comment]
All I wanted to know was what cipher is used for the simple convenience methods. Found it here: https://github.com/bitwiseshiftleft/sjcl/issues/134#issuecomment-29355149
