### ISSUE TITLE
Decoding in other languages

### ISSUE THREAD

**Issue by jcillo** [bitwiseshiftleft/sjcl#135]
I have been unsuccessful trying to decode sjcl-encoded text in PHP using mcrypt. I've just been testing with aes. Maybe I'm missing a step, but every test with PHP/mcrypt still outputs gibberish, not the original plain text. If one were to use sjcl to encode text in the browser and send that over the wire, does one then also need sjcl on the back-end to decode it? If one has all the variables that sjcl uses/creates (i.e., the password or key, the IV, etc.), cannot one then use that to decode the cipher text in other languages?

**Comment by robocoder** [comment]
There is now a php 7.1.0 example in http://stackoverflow.com/a/41323920/1644312
