### ISSUE TITLE
Latest version not present on npm

### ISSUE THREAD

**Issue by glenjamin** [bitwiseshiftleft/sjcl#160]
The package.json version was bumped here: https://github.com/bitwiseshiftleft/sjcl/blob/a03ea8ef32329bc8d7bc28a438372b5acb46616b/package.json

This fix doesn't appear to have been published to npm, nor is there a git tag for v1.0.1

Would you be able to publish this please?

**Comment by clark800** [comment]
Any updates? If npm support is not helping with login issues after almost a year, you should be able to make a new user account and then go through the dispute process to have the package ownership moved to your new account: https://docs.npmjs.com/misc/disputes

**Comment by Nilos** [comment]
Sorry I totally forgot about this issue, published to npm a second ago!
