### ISSUE TITLE
Latest version not linked to from github page

### ISSUE THREAD

**Issue by moggers87** [bitwiseshiftleft/sjcl#176]
[This page](https://bitwiseshiftleft.github.io/sjcl/) links to an out of date version of this library (0.8, which is now two years old). I assume sjcl still supports use in web browsers, as well as node.js?

Also, there don't appear to be any tags for releases made via `npm` other than 1.0.0.

**Comment by ketamin** [comment]
https://api.github.com/repos/bitwiseshiftleft/sjcl/releases returns an empty array

We use the check against the github api to retrieve information of the latest release in our build-environment, these checks won't make sence against tags only.

**Comment by mkropat** [comment]
The version in github pages hasn't been updated in years: https://github.com/bitwiseshiftleft/sjcl/blob/gh-pages/sjcl.js

But the compiled version in the master branch seems to be updated regularly: https://github.com/bitwiseshiftleft/sjcl/blob/master/sjcl.js

Who knows who maintains it, but if you want to source `sjcl.js` on your page as an external resource you can find an up-to-date version hosted here: https://cdnjs.com/libraries/sjcl

**Comment by Nilos** [comment]
Updated `sjcl.js`for gh-pages. Thanks for pointing this out!
