### ISSUE TITLE
npm / CommonJS compat

### ISSUE THREAD

**Issue by ryanflorence** [bitwiseshiftleft/sjcl#19]
Would be great :D

**Comment by Tectract** [comment]
It's not working for me. Can't get browserify to play nice with sjcl for the life of me.

Can someone point me to a minified / browserified version of sjcl that contains a proper commonJS wrapper, please?

**Comment by Tectract** [comment]
sjcl doesn't seem ready to be used in a rails asset pipeline. I was able to get it to precompile finally, but I'm getting sjcl not defined when I try to use it in prod...

**Comment by Tectract** [comment]
hmmmmm, I got it working in prod, but I'm not sure how exactly.

I did 'npm i sjcl', then precompiled and it succeeded. Then I REMOVED node_modules/sjcl and it's now seemingly grabbing the sjcl.js version I have from public/assets/ and loading it ok. Still shaky but barely working...
