### ISSUE TITLE
Sources ignored when fetched using Bower

### ISSUE THREAD

**Issue by ramondeklein** [bitwiseshiftleft/sjcl#193]
Commit b44fe7e60efc5ab8317ff6eb7185688b4d74fe20 removed all sources when the library is fetched using Bower. This is bad practice, because this prevents debugging the package (I haven't seen it in any other package). Most modern websites use Grunt to deploy the proper source-files and do their own minification.

Another issue is that you cannot cherry-pick modules from SJCL. If you don't need all the encryption stuff, but you'ld like to use the (excellent) random generator then you must include a lot of additional files. Please consider to revert this commit...

**Comment by Nilos** [comment]
At the time the commit was created it was best practice to only ship compile artifacts in bower.
Reverted the commit.
