### ISSUE TITLE
SJCL PBKDF2 works fine without compress option, but with yui or closure doesnt work properly

### ISSUE THREAD

**Issue by SirBrain** [bitwiseshiftleft/sjcl#194]
Hi!

Im using sjcl PBKDF2 library ... if i use without compress option works fine, but i try to use yiu or closure compress options, i get incosistent results with the same code ... this is the code that i use ...

 var saltPBK=sjcl.codec.utf8String.toBits(document.LogIn.SltOne.value);
 var HashOne=sjcl.misc.pbkdf2(usrName,saltPBK,1000,2048);
 document.write (sjcl.codec.hex.fromBits(HashOne));

saltPBK is equal to:
4918cdbb233232661e97c915721c9f9e14a51d25c52f0a6e7419c6fc697b615bbeb6dde036cddefc5e038fce206b740281b8c3d351182391e07d42fda2e80b07b87121924534d53cd2a32049390cd28e73f90911f08082bc2a96aceb49b2a877399c25cc32985040388f8b02025c9e2f1365704df1a50fdb3c51291e8aabfe4a

usrName is equal to:
hello

The PBKDF2 correct salt is:
35bcd14aef88fe0b19ed20654121ba20805cc65eecd3f64b657a1f46991b76d13990becbdb12d2584b05f3779641b21f746e253851f859fb94050c9816898991c88ab4bbcc047f8a53694df1c33f4884c36375a9ea5c45eaad4f20b60e90e61dfd012926aec823cb82c1746624bf66faaaa04927111b1b6987909e5d9411d6b4e38654a31e14641f7c1a820af10ae97c0d4ebedb32b3fdbb81fb6d841dc25f58fd733ce38ce67c1ebb2b1b6b1a56281c5cbe5c8fb9d8d103934cb38fb099e6823beef2100afb37fceeab9cf819a4c10aa02b05a79cb2e1b44150e7be84e43af16c0dd49c750f50ca61c93e047807b3949c81296b6e9bd5e07e009d979bbce443

Someone knows How i can correct it???

Thanks!

**Comment by chilinux** [comment]
I am able to replicate the issue.  If I use SJCL without compression then I get results consistent with other PBKDF2 implementations.  If I enable compression then the results no longer match.

**Comment by chilinux** [comment]
SJCL git repo still seems to be based around Closure Compiler built on 2013/02/28 (version is just listed as "exported").  If it is built with Closure Compiler v20150920 then PBKDF2 seems to function correctly.

**Comment by Nilos** [comment]
Can you upgrade the Closure Compiler in a pull request?

**Comment by chilinux** [comment]
Created pull request.

Upgraded the closure compiler and modified the shell script to try to keep it up to date (provided that unzip can be found along with either wget or curl).

Also updated README/COPYRIGHT to reflect the fact that Google Closure Compiler and YUI Compress are not under the same licenses as SJCL.  Google Closure Compiler seems to be under the Apache 2.0 License and YUI Compress is partly under BSD and partly under MPL.

It should be noted that a default configure of SJCL will cause 9 warnings with the v20150920 Google Closure Compiler.  If it is configure --with-all then that goes to 25 warnings.  In neither case is any errors produced and I am not seeing any problems with the results in my own use.

if you want, I can open another issue with the 25 warnings.

**Comment by Nilos** [comment]
As the closure compiler is now updated, is this issue fixed?

**Comment by chilinux** [comment]
I have not noticed the issue any longer when using the closure compiler
which has been my focus.  I don't know what impact yui compressor may have
as I haven't included using that in my project.
