### ISSUE TITLE
Unable to use sjcl.mode.cbc ..

### ISSUE THREAD

**Issue by jcalfee** [bitwiseshiftleft/sjcl#198]
I was able to `configure` and `make` with cbc enabled.  I'm having a hard time using it though by following examples.  Would you please check and see if this is a bug in my environment or if I'm using it incorrectly.  

http://stackoverflow.com/questions/26640511/stanford-javascript-crypto-library-sjcl-how-to-build-sjcl-js-and-include-the

**Comment by johnjelinek** [comment]
This does not work for me. `console.log(sjcl.beware);` results in `undefined`.

**Comment by Bren2010** [comment]
@johnjelinek Have you compiled your sjcl.js with CBC support? ([Ref](https://github.com/bitwiseshiftleft/sjcl/wiki/Directly-Using-Ciphers#cbc))

**Comment by johnjelinek** [comment]
I have to compile it? I can't use what comes from npm w/ cbc support?

**Comment by Bren2010** [comment]
Yes, you have to compile it.

**Comment by ggozad** [comment]
Since this arrises once in a while, wouldn't it be better if the sjcl package on node was compiled with ``--all``?
