### ISSUE TITLE
How to build an unminified copy of sjcl.js

### ISSUE THREAD

**Issue by nominify** [bitwiseshiftleft/sjcl#207]
@bitwiseshiftleft  How can I edit the make file to build an unminified copy of sjcl.js?

If I clone the repo from Git, there is a file called core.js. Is that everything in its unminified state?

Ideally it would be good if you provided an unminified/unobfuscated copy of sjcl.js alongside the minified version. Reasoning is that it: 
* Saves users time building the library themselves
* Is debuggable in the browser by stepping through the code
* Easily verifiable in a security code audit
* Encourages users of the library to use the trustworthy/more open JavaScript source, rather than relying on minified/obfuscated code which could have been built to hide something malicious inside.

**Comment by bitwiseshiftleft** [comment]
Yes, core.js is the unminified version.

**Comment by Nilos** [comment]
You can also do 
```
./configure --compress=none
make
```
to get an unminified version of sjcl.
