### ISSUE TITLE
sjcl.decrypt does not work with empty salt values

### ISSUE THREAD

**Issue by fruiz500** [bitwiseshiftleft/sjcl#211]
Example (from Chrome JS console):

iv="oiu98760987LJKHGLKJ"
> "oiu98760987LJKHGLKJ"

cipher=sjcl.encrypt("key","text",JSON.parse('{"iv":"' + iv + '","salt":""}'))
> "{"iv":"oiu98760987LJKHGLKJ=","v":1,"iter":1000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"","ct":"GgVybwDQV4X6ujZm"}"

sjcl.decrypt("key",cipher)
> ccm.js:87 Uncaught sjcl.exception.corrupt {toString: function, message: "ccm: tag doesn't match"}

(sorry about my Markdown, or lack thereof)

I think the problem lies with convenience.js. If I just use an old version of this file (say, December 2012), it works fine.

**Comment by fruiz500** [comment]
I've found that the version of Sept 11 2014 (33a6bbd) still works, but the one of Sept 12 (3c8fe5b) does not. Allegedly, the later change was to undo the previous change, but there is a difference in line 208 of convenience.js:

old code:
if (!(m=a[i].match(/^\s*(?:(["']?)([a-z][a-z0-9]*)\1)\s*:\s*(?:(-?\d+)|"([a-z0-9+\/%*_.@=\-]*)"|(true|false))$/i))) {

new code:
if (!(m=a[i].match(/^(?:(["']?)([a-z][a-z0-9]*)\1):(?:(\d+)|true|false|"([a-z0-9+\/%*_.@=\-]*)")$/i))) {

I put the old code into the latest version and the error persists. so likely there are other later changes that cause trouble. Otherwise I'd branch it and correct it myself.

**Comment by fruiz500** [comment]
The error is actually introduced in 514b1f6. The previous commit has the error because of a "raw: false" default in line 11 that causes it to fail JSON check, but works fine if that is removed.

Commit 514b1f6 introduced these lines into convenience.js, beginning with line 213:

      } else if (m[4]) {
         out[m[2]] = m[2].match(/^(ct|salt|iv)$/) ? sjcl.codec.base64.toBits(m[4]) : unescape(m[4]);
      } else if (m[5]) {
       out[m[2]] = m[5] === 'true';

replacing a simple }else{

I have no idea what's the point of these changes, but they make it impossible to use an empty salt in sjcl.decrypt

**Comment by fruiz500** [comment]
A pull request has been issued for a fix. If the simple if(m[4]) check is replaced by a more detailed if(m[4] != null), then the next line is executed even if m[4] is empty (as opposed to null), and the problem goes away.

**Comment by Bren2010** [comment]
I was able to get it to work with:  ```sjcl.decrypt("key", ct, {"salt": ""})```
but I wouldn't recommend that because you're passing in your key as a `utf8String`, and it's still going through PBKDF2 with an empty salt, which is possibly just wasting cycles if it already has enough entropy.  Whereas, if it doesn't have enough entropy *already*, then it needs to go through PBKDF2 with a non-null salt.

I think perhaps a cleaner way to do what you want would be to pass in the `bitArray` of the actual key that you want, similar to the way that you would with the raw `prp` interface.  Because you're generating your own keys, the `bitArray` has to have the correct length (for AES, 128 or 256 bits), but that's the only caveat.

In my mind, that has a nice, clean distinction of passing in a string and having it treated as a low-entropy password, or passing in a `bitArray` and having it treated as a fully-fledged key.

```javascript
password = sjcl.random.randomWords(256 / 32)
ct = sjcl.encrypt(password, "Hello World!")
pt = sjcl.decrypt(password, ct) // Hello World!
```

Would that solve your problem?

**Comment by fruiz500** [comment]
Yes, sjcl.decrypt("key", ct, {"salt": ""}) works. Thanks!
But I still don't like it, since it forces me to supply the salt separately from the rest of the ciphertext object. This is onerous because in many instances the salt is not empty.

It would be more elegant if sjcl.decrypt just could take an empty salt embedded in the ciphertext objet, as it used to. The only thing that is needed is one subtle change in convenience.js, in line 213, so that it reads:
} else if (m[4] != null) {
rather than:
} else if (m[4]) {

I believe the current syntax has introduced a bug, since the purpose of the statement is to detect that m[4] exists. With the current syntax, an empty value of m[4] is interpreted as non-existent, which is incorrect.

**Comment by Bren2010** [comment]
Yeah, you're right, that is a bug in SJCL's JSON implementation.  I was just saying that the reason you're having issues is because you're fighting against SJCL's programming to use strings as passwords, and that using a `bitArray` would avoid that.

**Comment by fruiz500** [comment]
@Bren2010. Thanks for pointing this out. I wasn't aware that pbkdf2 is skipped in sjcl.encrypt and sjcl.decrypt if the key is entered as a bitArray. Perhaps this should be mentioned in the documentation. I implemented your suggestion in my own PassLok app, and it works great. The new version runs faster an more reliably by using bitArray keys.

**Comment by Bren2010** [comment]
Glad to have been able to help.  :)

Documentation updated:  [Current](https://github.com/bitwiseshiftleft/sjcl/wiki/Symmetric-Crypto), [Diff](https://github.com/bitwiseshiftleft/sjcl/wiki/Symmetric-Crypto/_compare/064c59c49bbc7291ddf9e0b32fcfc54ff6df74c9...230073956e01f7921a76273daea708edf2c7392b)

**Comment by myselfgaurav** [comment]
hey need help to decrypt js code pls will will pay for task i have attched code

**Comment by Nilos** [comment]
@myselfgaurav not sure why you posted this here.
@fruiz500 closing this ticket as the issue seems to be resolved
