### ISSUE TITLE
sjcl.ecc not defined in sjcl.js

### ISSUE THREAD

**Issue by zoowar** [bitwiseshiftleft/sjcl#213]
I may be missing something, but sjcl.ecc is not defined in the top level generated sjcl.js.

**Comment by Bren2010** [comment]
Please see the documentation:
- [Getting Started](https://github.com/bitwiseshiftleft/sjcl/wiki/Getting-Started)
- [Asymmetric Crypto](https://github.com/bitwiseshiftleft/sjcl/wiki/Asymmetric-Crypto)

**Comment by zoowar** [comment]
./configure --with-ecc # did the trick

Just curious: Is there a reason why ecc isn't enabled by default?

**Comment by Nilos** [comment]
It adds quiet some bytes to the js file.
