### ISSUE TITLE
Bug in codeBase32.js

### ISSUE THREAD

**Issue by ogryb** [bitwiseshiftleft/sjcl#216]
It seems to me that there is a bug in sjcl.codec.base32.fromBits function: 

-for (i=0; out.length * BASE <= bl; )
+for(i=0; out.length * BASE <  bl; )

In the current release it can generate more Base32 chars than expected

**Comment by robyoder** [comment]
:+1:

**Comment by robyoder** [comment]
Specifically, when the number of bits is a multiple of 40, an extra `0` is appended to the base32 string. Every 40 bits should produce 8 characters, but exactly 40 bits is producing 9 characters, the last being `0`.
