### ISSUE TITLE
Allow deterministic PRNG

### ISSUE THREAD

**Issue by clark800** [bitwiseshiftleft/sjcl#217]
In our application, we would like to have deterministic unit tests of ECDSA signing logic. It would be nice if entropy collection was decoupled from the generator to support this. In particular, this line is hard to work around:

https://github.com/bitwiseshiftleft/sjcl/blob/2f591b4fcd0f96999c4985ca99ccb2154e94d476/core/random.js#L368

It would also help to have a method like `setEntropy` to discard auto-collected entropy and replace it with a given seed.

**Comment by Nilos** [comment]
** WARNING: this breaks all security **

You could simply stub the PRNG altogether by doing 
```JavaScript
sjcl.random = {
  randomWords: function (nwords) {
     var out = [];
     for (i=0; i<nwords; i+= 4) {
       out.push(44);
     }
    return out.slice(0,nwords);
  }
}
```

Maybe you would have to stub further methods.

**Comment by clark800** [comment]
I'm doing something like this currently, but it's not an ideal solution because it doesn't maximize coverage of the production code path.

This is essentially a design flaw in sjcl; a PRNG is supposed to be a deterministic algorithm, so the PRNG class shouldn't know anything about entropy.
