### ISSUE TITLE
Twofish at sjcl

### ISSUE THREAD

**Issue by quasiyoke** [bitwiseshiftleft/sjcl#219]
Are there any plans about implementing Twofish cipher? I've found several JS realizations on the web.

 1. [CryptoJS-based.](https://code.google.com/p/crypto-js/issues/detail?id=50)

    Original repository contains only one test — so, this implementation isn't tested. Triplesec's Twofish implementation is based on this one.

 1. [Implementation by Dario Andrei](https://github.com/wouldgo/twofish) is tested according to [Twofish paper.](https://www.schneier.com/paper-twofish-paper.pdf)

Quality of sjcl's code looks great. Authors involved in development are very famous. Do I understand it right: cryptography novices like me can't just adapt some of mentioned Twofish implementations into sjcl frames?

**Comment by Nilos** [comment]
The original creators are not working on sjcl any more, so no, twofish will most likely not be added.
No, that would be hard for you most likely. Also you would very likely make some bad mistakes.
