### ISSUE TITLE
ecc breaks random

### ISSUE THREAD

**Issue by animalillo** [bitwiseshiftleft/sjcl#223]
I've been trying to use ecc functions, but once you compile sjcl --with-ecc sjcl.random stops working.

Steps to reproduce:
1. Clone master
2. configure --with-ecc 
3. make

On the browser (tried with firefox and opera)
1. sjcl.random.setDefaultParanoia(10)
2. sjcl.random.startCollectors()
3. Move the mouse, or press some keys and the console will be filled with errors.
4. Try to generate some random words an you'll get a warning telling that you don't have enough entropy (as the collectors are dead)

**Comment by Bren2010** [comment]
I couldn't reproduce your issue on Ubuntu or Mac with this `test.html`:
```html
<script type="text/javascript" src="./sjcl.js"></script>
```

What OS are you on, how are you running SJCL, and what are the error messages?

**Comment by animalillo** [comment]
I'm running on windows with firefox 38.0.1.
The library seems to work when compiled without ecc, but if i compile it with ecc i can't use the random generator.
The errors are: 
>TypeError: this.f[g] is undefined sjcl.js:39:21
>TypeError: this.f[g] is undefined sjcl.js:38:206

**Comment by Nilos** [comment]
I can not reproduce it either, please provide more details and especially the compiled version of sjcl you are using! Maybe also provide the config.mk you are using.

**Comment by animalillo** [comment]
Ok, it's not a problem with the library itself, i've been experimenting a bit, and tracked a few incompatibilities.
I found it's incompatible with pwgen, and jsrsasign (4.7.1). Also it has some incompatibilities with our app somehow, i havn't tracked them down, but, here it's a plunked demonstrating the issue.

http://plnkr.co/edit/Tvu4DuyvNDXLSzUnwhne?p=preview

There go full screen, and input this in the console, then move the mouse over the page. (I dont know why is not loading the external libraries on my browser unless I go full screen in plunker).


```Javascript
sjcl.random.setDefaultParanoia(10);
sjcl.random.startCollectors();
sjcl.random.randomWords(1);
```

So it basically renders the library unusable with elliptic curve cryptography in our app, which would be neat, because it's mainly base in sjcl cryptography.
The app i'm triying to use ecc on its: https://github.com/brantje/passman.

**Comment by Nilos** [comment]
We have updated the build pipeline, can you try again?

**Comment by animalillo** [comment]
Sorry, I cant test this right now, we decided to use forge for asymmetric encryption as it seems to be working for what we need.
We will continue to use sjcl for symmetric encryption as it seems to work well and avoid re-factoring a lot of code.

**Comment by CrackerHax** [comment]
I am getting the same error... with and without compression. I would rather not use rng, is there a way to turn it off?

**Comment by dioptre** [comment]
This is still broken

**Comment by dioptre** [comment]
Tried repeating the test and it works with entropy:
https://github.com/bitwiseshiftleft/sjcl/blob/c1beeeee97c905e7c2da13e02308b46048f59437/test/ecc_conv.js #397
