### ISSUE TITLE
Cyphertexts created with 1.0.1 not compatible with 1.0.2 and up

### ISSUE THREAD

**Issue by demetris-manikas** [bitwiseshiftleft/sjcl#229]
Trying to upgrade from 1.0.1 -> 1.0.3 I realized that cyphertexts created with 1.0.1  are not immediately usable with higher versions of the library. 

The reason for that is that the treatment of adata has changed.
In 1.0.1 the result of an encrypt operation contains the adata that the caller passed in
In 1.0.2 and up the result of a  json.encrypt contains the adata encoded in base64.

I would not be saying anything about this had I not noticed that in the commits timeline there
is a commit on Nov 26, 2014 that reverts the change that introduces the incompatibility.

**Comment by demetris-manikas** [comment]
Thanks for the feedback :(
So long and thanks for all the fish.

**Comment by Nilos** [comment]
Sorry but somehow your issue went unnoticed. Can you link the commit in question?
Also this only changes the output and nothing internally, correct? So you would be able to upgrade your ciphertexts by calling 
```ct.adata = sjcl.base64.fromBits(sjcl.utf8.toBits(ct.adata))```

**Comment by demetris-manikas** [comment]
Thanks.

**Comment by demetris-manikas** [comment]
Hi again.
My problem is not as easily solved since I have to be able to distinguish
between
old and new clients since the library is also used in mobile apps and not
just the web.
I have found a way to do that but still I think tah it was an unnecessary
breaking change.

Sorry, I did not see your request about the commit.
First one in
https://github.com/bitwiseshiftleft/sjcl/commits/master?page=3 right now

The only commit on Nov 26, 2014

sha: f7f74c0129cac98dbfd2ec68748c30cdcbd51936 If am I not mistaken.

I think this was an unnecessary breaking change that should change the
major version since
there is no backward compatibility.

Thanks again.


f7f74c0129cac98dbfd2ec68748


On Thu, Sep 3, 2015 at 1:41 PM, Demetris Manikas <demetris.manikas@gmail.com

**Comment by Bren2010** [comment]
The reason for the breaking change was an asymmetry between `json.encrypt` and `json.decode`.  In encryption, we would sometimes base64 encode `adata` and sometimes not, and there was no way for `json.decode` to know which happened and what it should feed to the MAC.

Unfortunately, there's no way for us to add backwards compatibility for you more gracefully than you've been doing for yourself.  We'd have to try decryption/decoding:  If there's an error, try again with modifications.

Sorry about the catch-22.  :/
