### ISSUE TITLE
Can't get SJCL to play nicely with webcrypto.subtle AES-GCM mode

### ISSUE THREAD

**Issue by tracehagan** [bitwiseshiftleft/sjcl#236]
I'm attempting to use SJCL in an iOS web app since AES-GCM isn't supported, but I can't get it to play with the native webcrypto.subtle AES-GCM on Chrome. I'm trying to encrypt an array of bytes. I hash the password with SHA-256 and use that as the key, but when fed into SJCL it says invalid key size.

Perhaps someone here has some example code that will allow me to use AES-GCM with an SHA-256 hash as the key that is compatible with webcrypto.subtle?

Help is much appreciated.

**Comment by Nilos** [comment]
You closed this issue almost immediately. If you found a solution can you share it with everyone on here?

**Comment by tracehagan** [comment]
```javasript
var password = "password";
var passwordbytes = [];
var hashbytes;
var cryptokey;
var iv = window.crypto.getRandomValues(new Uint8Array(16));

for (var i = 0; i < password.length; ++i){
  passwordbytes.push(password.charCodeAt(i));
}

var encryptme = "This is a test. Do not worry as this is just a test.";

window.crypto.subtle.digest({name: "SHA-256"}, new Uint8Array(passwordbytes)).then(function(hashval){
  hashbytes = hashval;
    window.crypto.subtle.importKey("raw", hashval, {name: "AES-GCM", }, false, ["encrypt", "decrypt"]).then(function (key){
      cryptokey = key;
      var prp = new sjcl.cipher.aes(sjcl.codec.bytes.toBits(new Uint8Array(hashbytes)));
      var encrypted = sjcl.codec.bytes.fromBits(sjcl.mode.gcm.encrypt(prp, sjcl.codec.utf8String.toBits(encryptme), sjcl.codec.bytes.toBits(iv)));

      window.crypto.subtle.decrypt({
        name: "AES-GCM",
        iv: iv
      }, cryptokey, new Uint8Array(encrypted)
    ).then(function(msg){
      //console.log(new Uint8Array(msg));
      console.log(String.fromCharCode.apply(null, new Uint8Array(msg)));
    }).catch(function (err){
      console.error(err);
    })
    })
  })
```

You'll need to include the codec.bytes file. Also, the issue was that not everything was converted to bitArrays. Stupid mistake, I know, but took me two full days to find! I had given up when I posted this but did just a few more minutes of investigation and figured it out.
