### ISSUE TITLE
The minimized version sets s = undefined in global scope

### ISSUE THREAD

**Issue by fuzzyducky** [bitwiseshiftleft/sjcl#242]
The minimized version of sjcl sets things in global scope, which will cause problems if there are collisions with the minimized variable names.

Please see https://jsfiddle.net/ocnbaxhh/6/

https://raw.githubusercontent.com/bitwiseshiftleft/sjcl/master/sjcl.js#23cd0dee310a339b5b40e32924f0e91cd27967c6

**Comment by Nilos** [comment]
I know, will have to update the build pipeline ... it is quiet old!

**Comment by Nilos** [comment]
The build pipeline has been updated, can you check again?

**Comment by fuzzyducky** [comment]
I compared https://raw.githubusercontent.com/bitwiseshiftleft/sjcl/9008cb3c6e60a2edb924b439426c68ffcb7e993f/sjcl.js
to the newer
https://raw.githubusercontent.com/bitwiseshiftleft/sjcl/8a3f83d3dc774afcc10787f6108047eb75590401/sjcl.jsLooks and it looks fixed and fiddler check passed as well.

Thanks!
