### ISSUE TITLE
I forked and implemented progressive AES-OCB2, should I create a pull request or should it remain as a fork?

### ISSUE THREAD

**Issue by gyf304** [bitwiseshiftleft/sjcl#247]
I implemented this since it will allow larger files/blobs to be encrypted with ease. For example - with progressive encryption, one can encrypt files while uploading completed parts.

I need it for one of my projects, so I implemented it.

https://github.com/gyf304/sjcl/blob/master/core/ocb2progressive.js

Tests passed.
![image](https://cloud.githubusercontent.com/assets/7296537/10714290/c974a312-7abe-11e5-9960-372e5d7d174e.png)

**Comment by Nilos** [comment]
Please create a pull request! I am not 100% sure we will merge it but it looks interesting in general!
