### ISSUE TITLE
ECDSA verification of signatures: What parameter format is expected?

### ISSUE THREAD

**Issue by Qqwy** [bitwiseshiftleft/sjcl#251]
I have generated signatures using the Ruby 'ecdsa' (https://github.com/DavidEGrayson/ruby_ecdsa) gem. I want to verify them with Javascript/sjcl.

The documentation(http://bitwiseshiftleft.github.io/sjcl/doc/symbols/sjcl.ecc.ecdsa.publicKey.html)  is however not very clear about the format that the input to sjcl should have.

 - Is there a way to convert a compressed public key to a normal public key? Or if not, how can I instantiate a big-number public key in sjcl?
 - Both the hash and the signature are supposed to be of the type bitArray. What does this mean? For the hash, I could understand if it would be `byteArray` (as in, an array of integer values in the range 0-255), but I am not sure.
 - The signature of ECDSA of course both has an `r` and an `s` field. the Ruby ecdsa gem can convert this to the DER format, but from the sjcl documentation it is not clear what format is wanted.

Thank you for your help. 

~Qqwy

**Comment by Nilos** [comment]
The best way to import a key is to convert all of its data (x, y) into hex and then convert them into a bitArray using `sjcl.codec.hex.toBits(hexRepresentation)`

Background:
When sjcl was created, Javascript did not yet have any typed arrays so sjcl uses Javascript Arrays and an own big number implementation. To store big data, it has a `bitArray` type, which is a classic javascript array.

**Comment by Qqwy** [comment]
Thank you. :-)

How do I use the signature? How does sjcl know how to split the signature data into `r` and `s`? Or am I required to pass these in separately in some way as well?

**Comment by Nilos** [comment]
Code here: https://github.com/bitwiseshiftleft/sjcl/blob/master/core/ecc.js#L515
Looking at the code, sjcl simply seems to split the signature parameter in half, using the first half as r and the second half as s.

**Comment by Nilos** [comment]
I'm closing this for now, as no more questions were posted.
