### ISSUE TITLE
P-521 public key not on the curve

### ISSUE THREAD

**Issue by ssmtlbn** [bitwiseshiftleft/sjcl#252]
In my application, I want to use the ElGamal encryption with the NIST P-521 curve. For this I have to serialize, store and unserialize the keys. But there is an error recreating the public P-521 key. It throws the exception `CORRUPT: not on the curve!`
The same procedure with another curve works great, for example P-384.

I have created [a fiddle showing the error](https://jsfiddle.net/n9p9dp0j/).

**Comment by Nilos** [comment]
You can't just simply concat the x and y coordinate. I am not sure why it works for P-384 but the correct code is:
```Javascript
// P-521
try {
    var pair521 = sjcl.ecc.elGamal.generateKeys(521);

    var pub521params = {
        x: pair521.pub.get().x,
        y: pair521.pub.get().y
    }

    var curve = sjcl.ecc.curves.c521;

    var point = new sjcl.ecc.point(curve, pub521params.x, pub521params.y);
    var pubKey521 = new sjcl.ecc.elGamal.publicKey(curve, point);

    console.info('P-521 key succesfully created');
} catch(e) {
    console.error('Failed to create P-521 Key: ' + e.message);
}
```

**Comment by ssmtlbn** [comment]
Thank you for your quick response, it seems to work so. But the concatenation of the x and y coordinate is described in the wiki on the page [Asymmetric Crypto](https://github.com/bitwiseshiftleft/sjcl/wiki/Asymmetric-Crypto) in the section *Serializing Key Pairs* and it works for all P-* curves except P-521.

Anyway...So what can I do if I want to serialize and store the keys? I think at the moment the only possible way is to serialize, store and unserialize the x and y coordinate seperately, right? See [updated fiddle](https://jsfiddle.net/n9p9dp0j/1/)

**Comment by Nilos** [comment]
Yes, is there any disadvantage in doing that?

**Comment by thibaut38410** [comment]
Hi, I just tried what @Nilos said : 
`var pubKey521 = new sjcl.ecc.elGamal.publicKey(curve, point);`

But then when I want to encrypt something with this public key like 
`var ct = sjcl.encrypt(pubKey521, "Hello World!");` 

I'm getting the following error `this.y.square is not a function`.

I believe this is because the sjcl.ecc.point associated to the pubKey521 object has these arguments
`
x : Array[17]
y : Array[17]
`

While for a correct public key generated with `var pair = sjcl.ecc.elGamal.generateKeys(521)` , it has these arguments: 
```
x : c
->limbs : Array[22]
y : c
-> limbs : Array[22] 

```

So how do you correctly create the public key from a point and a curve and use this public key for encryption ?

**Comment by takeshibaconsuzuki** [comment]
For anybody who is encountering the same problem, you need to serialize the 521s differently from the others. You need to concatenate the serialized x and y, instead of concatenating the x and y before serializing:

    var ECC_KEY_SIZE = sjcl.ecc.curves.c521;

    var keys = sjcl.ecc.elGamal.generateKeys(ECC_KEY_SIZE);

    var pub_key = keys.pub.get();

    var b64_encoded_pub_key;
    if (ECC_KEY_SIZE == sjcl.ecc.curves.c521) {
        b64_encoded_pub_key = sjcl.codec.base64.fromBits(pub_key.x) + sjcl.codec.base64.fromBits(pub_key.y);
    } else {
        b64_encoded_pub_key = sjcl.codec.base64.fromBits(pub_key.x.concat(pub_key.y));
    }

    pub_key = new sjcl.ecc.elGamal.publicKey(
        ECC_KEY_SIZE,
        sjcl.codec.base64.toBits(b64_encoded_pub_key)
    );

    var encrypted_data = sjcl.encrypt(pub_key, 'this is a test.');
    var decrypted_data = sjcl.decrypt(keys.sec, encrypted_data);
    alert(decrypted_data);
