### ISSUE TITLE
not clear how this software is licenced

### ISSUE THREAD

**Issue by simbo1905** [bitwiseshiftleft/sjcl#253]
nothing about a license in the readme, no license.txt, and nothing in the api documentation which is linked to, no licence in the header of one of the source files i was reading. please make the license for this software unmissable. thanks!

**Comment by simbo1905** [comment]
Finally found it at http://bitwiseshiftleft.github.io/sjcl/ which says 

> SJCL is open. You can use, modify and redistribute it under a BSD license or under the GNU GPL, version 2.0 or higher.

Looking at http://opensource.org/licenses/GPL-2.0 it suggestions something like: 

> One line to give the program's name and a brief idea of what it does.
> Copyright (C) <year> <name of author>

Also looking at http://opensource.org/licenses/BSD-2-Clause it also suggests: 

> Copyright (c) <YEAR>, <OWNER>
> All rights reserved.

This suggest that you should be adding a license.txt asserting copyright, the year, and attributing some authors. Then I can use your lib by displaying some attribution back to you.

**Comment by Nilos** [comment]
If you make a PR for it, I will merge it quickly, otherwise give me a week of time to look into it in more detail!

**Comment by simbo1905** [comment]
Happy to make a PR if you tell me who to assign copyright to. I will set one up and you can let me know if I guess wrong.

**Comment by evilaliv3** [comment]
also from my point of view its not clear how the library is licensed.
i think you shoud go for one license and that's it or this confusion whant help.

in addition that clear license should be published in the bower.json and package.json; you can keep these as references:
https://github.com/globaleaks/GlobaLeaks/blob/master/client/bower.json
https://github.com/globaleaks/GlobaLeaks/blob/master/client/package.json

doing what i'm suggesting you will be able to expose the license on the npm/bower packaging systems and on the related webpages like: https://www.npmjs.com/package/sjcl; you can see that now the license is marked as none.

**Comment by Nilos** [comment]
"SJCL is open. You can use, modify and redistribute it under a BSD
license or under the GNU GPL, version 2.0."
