### ISSUE TITLE
encrypt output

### ISSUE THREAD

**Issue by cullsin** [bitwiseshiftleft/sjcl#255]
Hello, 

I have got the below output from sjcl. I would like to store the encrypted value into the database. 
Do I need to store the entire value below ?  

{"iv":"ugj1ETz2FwUey6MuipRxmQ==",
"v":1,
"iter":1000,
"ks":128,
"ts":64,
"mode":"ccm",
"adata":"raja",
"cipher":"aes",
"salt":"UwyjlyP0qmI=",
"ct":"C4/O083x7On3EofK"}

Thanks,
Raja K

**Comment by Nilos** [comment]
You do not have to store all of them, the important attributes are ct, salt, adata and iv.
The other values are the default values currently used. If you do not store them, you might run into trouble if the default is changed in future versions.
