### ISSUE TITLE
sha1 in sjcl

### ISSUE THREAD

**Issue by lkananowicz** [bitwiseshiftleft/sjcl#257]
Hi.

I am using npm to deal with JS dependencies in my project. I want to use sjcl, but I noticed that sha1 is not included in sjcl.js. It is however in sjcl/core/sha1.js. Is there any way I can build sjcl node module with sha1 functionality included?

Best Regards

**Comment by Bren2010** [comment]
https://github.com/bitwiseshiftleft/sjcl/wiki/Getting-Started
https://github.com/bitwiseshiftleft/sjcl/wiki/Symmetric-Crypto#hashing
