### ISSUE TITLE
Implementing convenience tests 

### ISSUE THREAD

**Issue by hunjohns** [bitwiseshiftleft/sjcl#258]
Hey guys, 
I am an undergrad doing research and am exceptionally new to javascript as well using the sjcl.  I need to get timings for different parts of the sjcl, specifically the ecc library however I cannot figure out how to implement these tests and cannot find any info on implementing the unimplemented convenience tests.  Currently about half of the convenience tests are implemented and running fine but its the half I don't need :P 
I have tried configuring --with-all and then running make but that's not helping. 

I would really appreciate any help.

**Comment by mereckaj** [comment]
You could run sjcl on v8 and use its profiler. I have tried it and it returns quite interesting statistics. (http://blog.jetbrains.com/webstorm/2015/05/node-js-profiling-in-webstorm-part-1-cpu-profiling/)

**Comment by Nilos** [comment]
Using `./configure --with-all` and `make` should give you a sjcl file with all methods implemented.
If I run the following all tests are executed:
```
./configure --with-all
make
make test
```

**Comment by hunjohns** [comment]
I ran those lines on a fresh clone of the sjcl
here's a screen shot of what it's giving me:
![image](https://cloud.githubusercontent.com/assets/14854208/11460932/d5def3dc-96c5-11e5-8037-ed52eee09ff4.png)

**Comment by Nilos** [comment]
Can you show us the output of the configure and make command?

**Comment by hunjohns** [comment]
![image](https://cloud.githubusercontent.com/assets/14854208/11461051/ebecabfc-96c9-11e5-910b-2c2587ff1519.png)

**Comment by Nilos** [comment]
The configure command is not running correctly.
I don't know what command line you are using but you need to install perl to make the configure command work (It was written in perl, don't ask me why :laughing: )

**Comment by hunjohns** [comment]
I am in powershell. 
What do you mean by that though? 
I downloaded perl but I am not sure what your implying I am supposed to do with it.
Sorry bout the dummy questions I extremely don't really know what I am doing.

**Comment by Nilos** [comment]
I am not accustomed with powershell at all, sorry.
The configure script was written in perl, if you can not run it on your machine, you could also put the following into `config.mk`:
```
SOURCES= core/sjcl.js core/aes.js core/bitArray.js core/codecString.js core/codecHex.js core/codecBase32.js core/codecBase64.js core/codecBytes.js core/sha256.js core/sha512.js core/sha1.js core/ccm.js core/cbc.js core/ocb2.js core/ocb2progressive.js core/gcm.js core/hmac.js core/pbkdf2.js core/scrypt.js core/random.js core/convenience.js core/bn.js core/ecc.js core/srp.js core/ccmArrayBuffer.js core/codecArrayBuffer.js core/ripemd160.js 
COMPRESS= core_closure.js
```

**Comment by hunjohns** [comment]
*transdigital knuckle-bump* you are my hero.
