### ISSUE TITLE
Please publish updated sjcl-all and sjcl-full packages in npm repository

### ISSUE THREAD

**Issue by Polve** [bitwiseshiftleft/sjcl#272]
When 1.0.4 is out, please publish all the packages, right now sjcl-full is still at 1.0.0 and sjcl-all is at 1.0.1

**Comment by Nilos** [comment]
As I am not the maintainer of those npm packages, there is not much I can do about it. Sorry!

**Comment by ggozad** [comment]
A suggestion:
I am guessing there is no reason for sjcl not to be compiled with all for the node version.
Alternatively, @Nilos you can dispute the ownership of the sjcl-full, sjcl-all packages on npm. I did it recently with my own packages, it was a very easy/painless process.
See https://docs.npmjs.com/misc/disputes
