### ISSUE TITLE
pbkdf2 memory leak in Edge

### ISSUE THREAD

**Issue by tererecool** [bitwiseshiftleft/sjcl#278]
Run the pbkdf2 code inside a web worker on latest Microsoft Edge Version inside a VM with only 1 core seems to be producing a memory leak, memory goes up infinitely. It happens in following line in the pbkdf2 class:

ui = prf.encrypt(ui);

This happens using a count of 100000.

Running outside the worker or with other browser with 100T it works.

Strangely if the debugger is open it works.

**Comment by Nilos** [comment]
As this is a very rare non-debugable memory leak in only one browser I would like to ignore it for now.
If you have got a solution please submit a PR, even though it looks like this is not a sjcl  bug but rather an edge bug.

**Comment by yaleidev** [comment]
memory leaks

**Comment by yaleidev** [comment]
sjcl.encrypt and sjcl.decrypt lot of memory leaks
