### ISSUE TITLE
Include Unminified and Minified Versions in Tagged Releases

### ISSUE THREAD

**Issue by xcthulhu** [bitwiseshiftleft/sjcl#279]
It would be convenient if both unminified and minified versions of this library were included in tagged releases.  Likewise, I am somewhat confused: there's no tagged release 1.0.4 but that appears to be the version the docs refer to.

**Comment by xcthulhu** [comment]
As I dive into the code I am starting to understand why you don't do this. Evidently there are a bunch of scripts to get rid of references to `window` and constants that you use to both pre- and post-process your code before and after compression.

Perhaps, rather than doing this, the code could be refactored to avoid references to `window` and so on?

**Comment by Nilos** [comment]
Can you be more specific? I am not sure what you are talking about.
This project is rather old, so I am usually not touching the build pipeline but adding an unminified version should be possible.

**Comment by xcthulhu** [comment]
If I type `make` on the top level, a file `core.js` is written.

Now, if I try to use `core.js` in the unit tests, it fails.

This is because it refers to `window` which doesn't exist on node.js (but does in, say, Chrome).

You can see that references to `window` are removed with a perl script:
https://github.com/bitwiseshiftleft/sjcl/blob/master/compress/compress_with_closure.sh#L32

Anyway, you can close this issue with *WON'T FIX* if you want, since redoing the ancient build system for this is a pretty big job and doesn't really win anything.

**Comment by Nilos** [comment]
You are indeed correct. Seems to be something the closure compiler does.

Anyhow you can create an unminified build by changing the `COMPRESS` option in `config.mk` to `core.js`

**Comment by xcthulhu** [comment]
Not exactly... if you change it to WHITESPACE_ONLY then the result does not pass the unit tests.

What *does* work is SIMPLE_OPTIMIZATIONS
