### ISSUE TITLE
CCM: Tag not computed correctly on initial call to decrypt (latest Canary)

### ISSUE THREAD

**Issue by MaKleSoft** [bitwiseshiftleft/sjcl#280]
A weird bug has popped up when using sjcl in the latest version of Google Chrome Canary (`Version 51.0.2698.0 canary (64-bit)`). For some reason when calling `sjcl.mode.ccm.decrypt()` for the first time after loading the script, the tag is not computed correctly and the decryption fails. On every subsequent call everything works fine. Here is an example:

```js
function testDecrypt() {
  var key = '984LZT0tcqQQjPWr6RL/3Xd2Ftu7J6cOggTzri0Pb60=';
  var iv = '5mdFbbnTJbHSp11Ee/u9nQ==';
  var ct = 'fXSdX+OO+YnKhfzKfb0DT7CIOQ==';
  var adata = '1gJqY1uowoD1YRWKH/qS9A==';
  var toBits = sjcl.codec.base64.toBits;
  var aes = new sjcl.cipher.aes(toBits(key));
  var pt = sjcl.mode.ccm.decrypt(aes, toBits(ct), toBits(iv), adata, 64);
  console.log(sjcl.codec.utf8String.fromBits(pt));
}

try {
  testDecrypt()
} catch(e) {
  console.error(e.toString());
  testDecrypt();
}
```
Output:
```sh
"CORRUPT: ccm: tag doesn't match"
"hello world"
```
And a live demo (It uses v1.0.0 but the problem persists in the latest version): https://jsbin.com/wiworadeja/edit?js,console

**Comment by Nilos** [comment]
Is this till a problem? Sounds more like a Chrome Bug to me.

**Comment by MaKleSoft** [comment]
Hm, the issue seems to have disappeared in both `Chrome Version 51.0.2704.79 (64-bit)` and `Canary Version 53.0.2753.0 (64-bit)`. I agree that this looks like a temporary bug in one of the Chromium builds. Anyway, there is no way to reproduce this now so might as well close this issue.
