### ISSUE TITLE
Unserialize Import/use ECC key to encrypt

### ISSUE THREAD

**Issue by thibaut38410** [bitwiseshiftleft/sjcl#281]
Hi, 
I'm trying to import an EC-Elgamal public key created from JAVA. I get the public key from the response variable and then split it in two in order to have the x and y coordinates of the point and create a point on the curve from these coordinates (like advised here #252).
 
The following code works great until the last line at which I get the error.
`sjcl.js:83 Uncaught TypeError: this.y.square is not a function
sjcl.ecc.pointJac.doubl @ sjcl.js:83
sjcl.ecc.point.multiples @ sjcl.js:80
sjcl.ecc.pointJac.mult @ sjcl.js:84
sjcl.ecc.point.mult @ sjcl.js:80
sjcl.ecc.elGamal.publicKey.kem @ sjcl.js:98
sjcl.json.ta @ sjcl.js:53
sjcl.json.encrypt @ sjcl.js:54
display_data @ EC.php:95`

I believe this is because pubKey521 is not seen as a valid publicKey but why is that ? 
`                  
                                
				var response=xhr.responseText;

				pub = sjcl.codec.hex.toBits(response)

					var curve = sjcl.ecc.curves.c521;

					var pub521params = {
						x: pub.slice(0,17),
						y: pub.slice(17,34)
					}		
					
					var point = new sjcl.ecc.point(curve, pub521params.x, pub521params.y);
					
					pubKey521 = new sjcl.ecc.elGamal.publicKey(curve, point);

					var ct = sjcl.encrypt(pubKey521, "Hello World!");

**Comment by Nilos** [comment]
Quick hint: x and y need to be `sjcl.bn` instances. Long answer later if necessary.

**Comment by thibaut38410** [comment]
Oh right I see ! So how can I get my $pub variable transformed into a sjcl.bn instance ?
I'm sorry I'm new to JS but I guess this should be easy to do ?

**Comment by Nilos** [comment]
`new sjcl.bn(x)`

**Comment by thibaut38410** [comment]
With x being what ?

**Comment by Nilos** [comment]
Actually you would have to do the following:
```
var pub521params = {
  x: curve.field.fromBits(pub.slice(0,17)),
  y: curve.field.fromBits(pub.slice(17,34))
}
```

**Comment by thibaut38410** [comment]
Wonderful ! Thank you !!

**Comment by thibaut38410** [comment]
Still in the same goal, I'd like to import the secret key from JAVA but it is in two parts P1 and P2 on which I have to do the following computation. 
```
var P1 = new sjcl.bn(1760155568381108077728955525466304625001925036115713794685310868342880476362669297036446701554368919223527049607901133589676711066745561126839701832108418842)
var P2 = new sjcl.bn(2474462426577380421316091621769392571173109603759599561152952261614422810035340163276008365069819954978724498004960765804352991836744173010970041467851878297)

var privateKey = P1.doubleM().sub(P2).mod(order);
var sec = new sjcl.ecc.elGamal.secretKey(curve, privateKey)
```
However, the first operation `P1.doubleM()` does not return the correct result but it seems to be correct if I declare P1 and P2 as hex values. Any idea on what is going on ?



Also, it seems I cannot decrypt a ciphertext created with 
```
var point = new sjcl.ecc.point(curve, pub521params.x, pub521params.y);
pubKey521 = new sjcl.ecc.elGamal.publicKey(curve, point);
ct = sjcl.encrypt(pubKey521, "Hello World!");
```
even if I hardcode the privateKey as an hex value. When doing 
```
var sec = new sjcl.ecc.elGamal.secretKey(curve, privateKey)
var pt = sjcl.decrypt(sec, ct);
```
I get an `sjcl.js:24 Uncaught CORRUPT: ccm: tag doesn't match` error. I guess this is because of the different keys format used in the encrypt and decrypt method ?

**Comment by Nilos** [comment]
Javascript has no native support for large numbers so if you write a large number into JS it will be truncated. Meaning that this: `1760155568381108077728955525466304625001925036115713794685310868342880476362669297036446701554368919223527049607901133589676711066745561126839701832108418842`
will not lead to the number you inputted but the closes representable number! That is why sjcl uses hex or base64 for number representation
