### ISSUE TITLE
EC + ElGamal encryption/Decryption method 

### ISSUE THREAD

**Issue by thibaut38410** [bitwiseshiftleft/sjcl#282]
Hi, 

I'm wondering what is the encryption and decryption method used when you compute a cipher with 
```
pubKey521 = new sjcl.ecc.elGamal.publicKey(curve, point);
var ct = sjcl.encrypt(pubKey521, "Hello World!");
```
When taking a look at the encryption method code, it look likes it's the same method used for AES, ElGamal and many others while I think the correct encryption scheme for EC + Elgamal is this one http://crypto.stackexchange.com/a/9990
But then, what computation is done when passing an elGamal public key as the first argument of the encrypt method ? And should I code the ECCElgamal encrypt and decrypt function by myself ?

**Comment by Nilos** [comment]
sjcl.encrypt is a convenience method working with different crypto schemes depending on the key (password, key or ECC-Key) input. It internally uses the `kem` method of the key provided if the key is an ecc public key: https://github.com/bitwiseshiftleft/sjcl/blob/master/core/convenience.js#L49
