### ISSUE TITLE
postmessagerelay.js.encrypted

### ISSUE THREAD

**Issue by davinad1472** [bitwiseshiftleft/sjcl#283]
please help me decrypt  

iACkFVRoBlfkmMTv3D0/CyaDWlt23WF0NTF0yNeq97z5JLx/kBZa1hICVMeLuIAkaLc5ukZu893CaLPLuoazKGOEdCHOIxoCxTrxCHhYHsJoNdscbByUAnqSpCNM4AVrNTld1kCllVlkYpdMuaaPvCOKfQ72GgCEKYS1Xtadnngrx4Bb+EFa0zykwqgvs8eiegSg43ko42wUqpUlBemPBavRLUYBJWjVKoheEoF7BSCR5GFvHv80p8D+tKyXbTw3qdfWhp6O8qvZDVZcqrs4LvACoOz8yQn/Qssy/zKa6y1WA2U8rGJnFFdt4Eel9RzECDxNd8LuEne+ouk7fyGTJy60/Ta/VHJiFVQR2bJ71RTU6SonjR3O1sHPGT6plan+0JZCrZRO9LYcKqQaB2HpwXQlDxut35oh+Mgo8y24DO/PJt6KOPxQj8rynOC61mZuGfQObQu20WenzhqdkkoDGn5PB7W5hHBDmXjPMG8yN9v3eRtPnptOi38g96L+wcooc4ugOiJ+2vmFuByIvqgwFcU5WFdbJVc/Mu25RgoL2OAwZhOaUy+jsBMdSZptPd7oK8Hckb1kdsVdLpnzGTIY03G2fFW/taxHQ6kg6m9CGkpYpoMLsXGUOp1d0GqzIkJXVHk2rOSvOxhuoBnJIsxmcmu89A3G3tBCov0mU/t8mFdDTG+kUbXuVb2OKEvRsI7nsWlufJ/gAGgeW7XnFLJmcIi/3dCVUVWYDPa46xHbC+mjdA67jCvc5o2IlylIhlJIqYZrXRyAmb2VxSVzCzLXcP5+WCgsc9m2cwjv71lsXVsnBlZc7AFdORHWM0WcWVsdWtOmxxb90XYAAICLFQkvIxA0AH4HCmmrpuMEOzL7osu+j6RIhUK0RDyBpkT8w/MPO6tVtSu3RwtBciDAy/5HFFYnoODYZ6ifltIpK487cXIy3aIZmw+CJwXj+Ds0Q7sUAdskkmmpjAOdQaD8OoxsGUm+keiRPdbH58YMk9Uqawipvs9OIqznMLVTS4npozcstyE1JZizNRCvAlu87NeuEAib8YRyKGCl05pGJy4xPMogiZu+zTMBcdCpXd01vex/1kVC6cB9shRYuMThREZMewElG+LUKRkelQrQYXjRCXMwb0VFaF0RNL+gsqwL/cfDJs4ghw5tVYYZLaelF6Tc7xjlkWQ2WEMMrTVaIjw9C2iKkQeaCdtp6Wc/LhlFO1af+FayQZU0Qn4KdqplGYMRv0lJ/kvGYZS33TUcRJL/MU0q40FSsmTw3Z+7eRLPuA8+QAX0TEJbXOFgQsPJWR/4Desy28q04rmSaaezKQWNr5Hy7oxsbOUXhCiZSp1cmTKq/OezEIu0rPNnIG8dBBeXmvMHJQvekovCmogRWrHCE9h3g3vZqNNaXS2CbKGYonAV45ONgdhbrXWG6mt+skh8ZNU1byssnuLdGFZ7HCMb7L4DDIlG6iVhpmnqpIs5robKmx3if4ed9K5C8GA0/9lvyfj7xpb5LrcRpNpoPQdFHUhUyGfAIC5kagnQKBVM+jWSNfLmXEYqKQjb/0IwXJfwaxenKyM/5GAchV35E6tzfxbUub7Ea1YooB88nOa2YMfi/G3sBFL5VOLBr6QLVucfVB4tCY2GK2iEjZhoPt3ZdE2+oTj22K+vRmdlguRjJtVNA/vCL1TrKXbI+rCMvAVSM5efFz9x/F+YzYJLdFEbFIE1bZ/ZUZm5oQlzcMHx2JzcA3Vye6u1voTOwcDSCWrtbhgUTPJ42DDKwvUB/lSjmGnwYiQgW+nT1UhtF+BqEW8hkWgPcE5QBudR5ugp/a/+gi0GTTjAiPbpmSgUB4r4OPPq0x2nqagyEL+zrAskNg3vX+5i19GMxmI9riNvrMtcVWNBEhESyn0cCNta1HN7xKLwRqHy9he66esoj1lGCjZYT7hI+OqGcaxmQepXSwimR0xmXX+c7xGjP7J1HyNmpqcqrRhFFbfFoiBO1Fsfrt99YeqLA0WZjZHQZo/k3oWcAEkdauCGOML8oIeoosfFZO0+mEdfEy1jliAKKkAiT64oWepG/IzBbxvgnASY3VDDQcVfSIhfZeCFkKeSMbTs+o2H0V5J38ZLGVgQWiVzj/weWp/13YYZjRhdm4l+4jT0s9iKbF8d03SElWK+o6KbZYbouI0BUtAcYAgckwEvRCPeRwLVW8LQPDqzYoR/TfYHTQIKLsfgrRbxIDhkA5ZCiRnOMjstRGWEUSKXRZwCOy7hwxi7p8Aw0r7FgGIELXqZgJh6Pd1+dg82gNaRUrJ2W9FPYpdTppaOhzsoqQuH7SE67LHmjmuNvhtVBvSmMGyVD28C4GGVACHWCjnweGYpbCBgOjxyviaNtdjzmnmwkUeGyI0kjCiyz3qQit5BkoeU4Q4RQQX3szGDHJhaf7tjOIgBV+Z/HUy71KjcuL0ul44W+if4F2aJfehjBTJ/Rd33zsGq6qRm9F8ApQCM2Tp/CUWpKwngq/iuY2/cPOVE/50GWvNV8TfcA3KdmYcamyq3Ox8/TrVMMdtNwvDOmA9p2ZU0Y00OEBQoXluMyXMDFqnr4YmuAVKmbQuHXu1PIUG+isz6gZ+yaLzDjTuOcHoC0EZ7Jv5TUVqP6TP43ZR1XAV39Kz+eAH+u/g4pJMa2zoeTsph9swD5xuBSFWHUXWHFXxCUDtqM898ahAl2ZgFVeGC/Hs+lS1Htf8Orwxf0ZUZB7t1nswKSzJmnMpDTGxH+6h9PY+6Edo6xqWvPEDEPZkwNRUUH7VWYH8UGzgGCIFGdI3ReplBGqlTQeOMWG5miHwykAXMfOLfbs7VES/0k3trNInJVW2LtCZb4fAjZZYCbUgbAeLEjKiWuIUAAkqy9Ut43B/0lOtuE9p6Y33NmuJrkEDO4qu+Hb4AvkZu+46Zw487q7yprya9SrRyQwPLRekiPIf6sa3uhnr+Mf5icrQALZeOirIVHdmup+y6bgbd1H4FAxY/h+5TgWYRkvJgdFMs85r8nzEGmZvh4kT3GXuJ4EHSjmOLtDXD8s4fH1vXqHra0fupDghBiyapW8X2T/GfpdRYCbgz01IXIdCFVN8alik/z5FVui+4aAMLe+EpVhmG+weZdZJlIX8vCrxVjp3m9uyqj/uji1BBbk197Bi2PUBiTFJyPGEbcBXfK38ytlvya5mojfAkBifm7cF29995G4hZSO1EF3MQLMGz3JN6dBgobHsaYoc6sKRtRixvIFnmxAxsdG394nt9ITPwtM2H7wgC6rUzyp8/SdhnpxG9pN8U95aWLVMaGMoqYkLhZsfuFx7EUMJZ1J8gE7G56Keov0xcqyu625hC1GROxlTGp52vTvl5iI9CsSQl8lI6bsnK62zTjlBYR3en8F9saEIAw3U8J6A26V0LCq2xx0vqQxTgtO9z0tA2FMw3Jsikng0sRx6LMFZ/XKgU6bGzASTGLlxrFSohlUrqb+SFxf+y9HfFHpOuhiuliJ38q6jNH4LKMioiqv+E0jhiA1n2u7nD2485ogwfny5EG5JaQ/OBS+h4IcKkSL4GyJRzdGDxwT3Mpmn4whfSkPaXU2uhdPyip++GI9tZb7mzxaDSVBfnOtlhy5EP5qGxkIMR6WV5e6+aegZgltesLVs7t99Y2BpLWPO1vvHqhJQJ9WAdo6jKWdubsVdWxlK7Dm4uZJB6cvJJhALG/87H+sPp/QttCunUulxHomHiCFzqOWyHt21k8PONgpWyr3pAuDlnzM4ZT6Bv/46ggOItq6FhYysUaXdJaqs5bInfapkBDxK0ezXfTKf9CicA+47MiG7ztsTNzG4/MJwnlU4qXHfbzZM1fnWia4Gaw7FYgKRKk67e7qXOou09qIAthHclOqLVKusCXedTXOG/sucxH2r7QioCQMpFsrs64V6TfUC+Ehn3FK03/iE66ia47U2VQF5KfxUeaDT6KArZ3AIJYvHV2tx0yTn13dvwzOJPRJ9A1GlzB1LUoFfb40QVjC6waOjmfylIFxIno6cDY67rd9c04pwrw9w+qJ+hxFMEkQieCLh6khJ3xc6ufIH6r0dQW9WtEXh9wmJEWgZzaSZHpnLeNh4p8N223S0gifOrD5nF4WlJjg7x1nwFShkmADHU6NZpMAk5Uw+WDWMhV3OkgrE7OkbSy0KeuXP4OuzIH7ajRW/LuSqDDN2ynezS+ovFajFN6BkcMmR/JIdTpILjq5CkBYtx4g8o+G+5D+klu1/2KhTGzKjWHrbZER7Jf932R/Doqp3jibQva4Q0YDOVDLm41C0GDbk6ie9zP28r3gA7kNKoYQ+8gaFyzOu7IGIyCNaDvadg9+7+UfVpB5WWJ8I+JXwt1RCUEkAgcv9yG8vtj71jiDnZGZb2xilrFmN23u2frDEt/239W/5N9z5AeayYwcOdjA76TPZjR6xtDk8sarzbXxjpEhrvN9ehmpgDFc/tAFPAkBrHvx1MOTE+YTeat5uRrw+AX29o/yBDsBXEDXsa3WwwAdNLBK4zgGw8GeNvpR4+7O0SkK6SecBhOAFDg00Gbc8ZthHtHczbLXTC1EEHSqjB2vZNjqmKshUkTYgLYjlwFsfbt14xKN01/VD6UjD0GuzGisjBlSs4VNjyq0s7quLe+hl0xOqHZEWHmVRvtuwxjIxTB5wYrJBuI1HJs7Bb9kPd1OtRNIrO09vJXHQQEhbLv2KFadyoBSsT/Gbb2N7Vz2KDdO5Ob5fhyAgftsEVXPtobkTbuRRFrCaUebajFWUQEp6Pqz43fEbYkD6gnXwEj1KHT1jjVs4MxI/4vtackiuPkCD/GZc3ixsLRWmaxHvEO/jpnUTzSb4xHGUxvcJCLBZf7RkY3+KD+Z6yU+0iMPiqtvDDofwpMLWArIKSJ2IvH/dIAsqDJWLSaRiKh7MEaTU10Zh34KVP5rZrewXM85yjupdSzNcx8rHk0TQk1JWKu06ZWTD3pCYB8L/iPUtOIAWO3yazOtvkK8Mn9BMKjzdQYpJ46Uc9W/LEl/f96pPCPWwufpwkTmtKt5vk0p29Rv5OyT4zqvDSDA/YaE0ljBr3IYNEaRgw0orr8grVz558XllZZVSlDkrqw28yO23RbiMAxZ5pycGycHoHJ3Q/C5UEMvyYvjRQ6ZgD4ynmuygCjkXjumjHa4T03OkFWpwRvtaZAOwFG4XaUD94m1A4avyknMozCgquI+M+skZn4vDVcVhYV+lMVJ+SQr/q4GDt+nflzCdwRpkDcRqB7f6QMADWW4ZP2digKuWaFHru/HoXCIKIl/1bMsLNXHqUoPsjuhZmD0reTItvQ252s65575s9bQKFvu/JBtHrfbWQnovSB43WyraptSJA0oD+jgHeknSMZMhLd1x9Kg2pF8KTR0SFgX6NFXkgAQfbbSZF6//JsxhfvUFQNursciwiYJIcQBXGyiH8C1NDeIZLJbyPhA/cRaZEPoSv9LHLgIiFUPfvBMAzLTJlv6xgFWohl85+FYeq3xfzTRYvSFzaQqn6KAQ1N/y6WvMRLcSJZLhQxXqdT8CfoqWujnf61spm8whA3IifjPvBvBgEbvUBoEu46E5ta2LPzhS6bIGObKmNDSMRzK/Zg7wwt5B0wHZv0+e/c/Xm/BhN4oIdU7DnswGMgzcp6T7k2MvZFhgj8YFpmBKPq+ZN/W/xJiUC+vYvLQemAVRjyA4qMfk6Pp5Y7cgWUYyZREgU5iHKB3MiKqD/ljj6Dm3UI8SwDjhtyN7hY757ke7JUoDSJGUNQuR+0BDlcPhK4OhTwJN6ReKEJzguWsoEndDDwLN1yWJYNSalsMAUmDNU9Xi2IDwD1tm9ka5nJdWHBfVhbQQUthEGK9ufMF5BfhhYnbA0ZrRfXLb+yCABgqkqhMAa1yTXBTb+si8P78UO6jLBcCjxkabKLIYdeWgi8SSc5sQ/d83v354CodMeOxZakS8iVjuV2g7Rmymagl4Y6E2nD6Geih/P/SmazwEQDu/+8g8J53OM0z3PGKB0rUg8QcoXUqYhk4sytdVXXtkSEqQhX6V2xv+gwvJ7E0zJOTBjYQN5jxABSRB5ERg5fsSdOnRUCOWRyeQUhrlAalpMwRs4CMA+6e/ZwJZp5CCqkVh9rkSk2KCHLpAW9gYtUbqGiMrh3aDZzXVOlV2AFmyBxZnyEAU1z5Mh7ThK3VEODqYHmscF6nkj8xxvQBeWnnuZMbFMnqLo35XgNHOXohU00EiHHvyl4QOtPlN1aLMUDKBFEtzHe5kTh02ruOHsC3cbP2MLL/8pLS90U132gp7xycxilinZENkwVD+6LjI8WqnrM2FNqkfGy0A1KEnicgVSKDhgFP56UcfzwKx7qNdyIMzvk0BOLtmcbpfsnU+XUnfzMYhwr7kV3Y7PBlLY6STPwCd+wLSxyNFkJiZ05r47KL5xRZRLXSuaKCaOnPed+FVjMecW+8W0heaflonkE2MEGsrFYC1nTTNaCUCAGKUxlKc0cgMrRBqHIVUTS7IQZh3MdtKcv4fPFy/FBGuJ80cSYElcYeNcpD6It9Aw+xcO+q7QRddGpYmX8qEbFpHFp8x8ruolSwLPUep1brIaN832wxK7Oj7lVC2nBBRDAB2WEYRHszRKP4vvLW9jWSsQsri7gsUfKmPq6ggVGg1tEo4uAo01R8YO2IgrNejLuEFO0sZnCauhhcH+AUo2kUVgCTqpZri1yabjpnlSx5R8eF8cPAUZbTniWPMc07XaBezmRWolkk7oG9NJdBeDEYhdE8SfgGZrYW80BcvUSTqsaCo8Y+aDlL8O5nVZl2m1JFJChiudGQSXWq21zaSMCILekKCPt3v4QNPOOo6UQ+BoiHRJKsZSqO0hLseiWY3loIIWSQrMY1ozp3UJnyPzlsMB2CxWPIVhvvHmvBSZ86ciyQgOtjOfW3FtENCw2+mVekBE8nViVQVY39zCXT7LnoPzP+rs5b+s7oTICi/tVwxmdZqbVRdxfHdYfF6J/pyPtEkW72caxnLPo4mAHR1dk0MNoiGTt3YAvyr5z6/0/G7aKwqpeO+xBkUMyp+AhOJPEP7/Z7XW2rpeiQUtZKcI/2L0axyItDKuBiad2qJXlxwtSQ02m9/Pdn1lhk3WGRiZQWIUI5E8YFskBkr93dVel61FRuinIUTQ3RtesXqzYsCa3Q+mpQrShrVlz99NVLI//MnvlVGzFj67ZMsRKqjdPZ+DGwIvAvVzZeE3i5xxvkBWEGYFRATwxS5jNFRtNsjpat2vCy8qgeHxvEtw2X7DI1tTNJ/7Leo1V4wH7sh9oOm/kbzwziDCnPVrowYpl3E6ZOL+eW7jpvn7Yg3XLUgr+PhvN0xrYDxmM/+bt6oscZkThV46ddhM55SZDaqlGTjkmQRMqJidpMbAGodWW9YPsXx+U+RUq0rpgsUCSVRJViUlMzcG0pUpzjsJb56NID/M8KT6qWqPYR0L0mpDHKbQwuiyrYDDMHMTakkV2NWHbApgxeXS/EtvDSA0N8OIdK7mvOLae6DllaMQBSRIX2cd8uBdWpyWrUstflsTZu5oQ3V7OoEyLkbr0hNr15AWPx/rwjsYq0We1P28MXFb38lZrgok9T4KMOKIULyTlosoibtTLOm+ChbcHZPlmIMzz3VXeyFnxqVQBtZNvq2lnTYh7IUTdQ9p1QGTJh0j1o8QoT07e3/r0/9r6yPQSY/kbutXFkw1vEVImY9n+P7o/6v+hpZVn+all/VdQlMtvWMd2NtASsfWOqrWmExern/cLtOHCNNSsxKxrPtWTF0bpHBQceM+gkucOqUIiePPVhhYOA2+lTPBLnUWAC/eZpjwNeXwTn/vWqF827WyOQ9hnzcT2nNgMmFbZVsuY7ijoaqvzEXli6gWtZ3LmPGmvQDL/1j8CITPpXCd5rbPrNQ37fYi4AXMR+NOO2+p+zr4jUiTMrxc+FDXPXjri1BixFrkBLVhuG2ZkBtVTrCQ/WXhbxYHDLBTV2DxKSbDU6RAV9ywj/IhgqiACVlp3FgGF9EzD/xeb+ZonBuCuoGvZQtulzhhFyRklogT1SsNLbq6G/+6DHfh2Lkw6uFJS1iZnNsKhX0xFELb57Eabt++oukMtecOGHc+4Ixc8QGZm/BsgDuFX7d8hSIoLSOh40x4MZeV34P1+YFaqCia0X9s8bqTJjjA/4PUlPLWTNRbutsw3z1FH5Wbob2ic13YnwBxrjvbCP+BKNFg78We2E/QVDKpTuZYzQvjUAwHYP1p/vjfbtMT9rjV4zmfekL/+ju+8dGcefXFq5T6KZMK/Btd7aq4LSmKYpS8T0g9wHgFUFGfyTyWu5JewTh4uNZrPDwkhc9hW2NJ0gPExfh+HLc4eEFdByFLH7kGkNvof7mkZUJYgfouJGtuOI4pWTfhwyrMalYrH7YaD+SMibWJoBPt+N0x6OOsE0+qVTn0PQ6qLgX/vdIuBA8I3Fc+HibHR4sLkTstMFUXDOEy56MVLvhS8pU7jFUFFZDnfVvZZtlo7BXOsuW/iml0V7kt0SvWjcSxkAcImk/NxRikYeoBrmWzmv/yWmggANCHORCr1tJ98fenjgxbqp2EBIsRvbKcgHuiOhgPRArhuvdEzq4OziTgDmI3xzrtaeBq9/IwLirQzzv3vFM7qysuxdzuq3sggEogdOjzFdO5t8hd9YcE6SDd8p3qrSY2HUDvraaGDT+C+JQsdffSDReF6DBj4NqEgwKzalPHPoK/Wd0D7WgHbSOQ0iNeaPK1VxXjbIypjr/EfZtnmpKMN+0K4nwaDLNXl7vwwcnFYvFLaVG7h4Z0/aXZhue8O6+nMS2m7X0x2oVy1GU/ITDp8JQOBt4X6h/YyE/GhBe0TTL8z+FdB0l7Jqo8pvbSlJBano9lblyOgojJYBIKlXHzS4Wl5bFDEDMZFR+vsJm0la4gjt3dAP/ZQs3fG5Gz2SBpkak5QkuOrXvN+lcCFD1yyYkfb3tpvf0Rh2+/9t3QJq+3jhSMxgxruOCDFHujRUmh26QcQK8K3sB9Jq2W9/2uqVN/ojMZEq+7XmSCcuictnMZhqwLPbctPde77s8tjWw2MNSnRPGxam7zZnZ5FdK3TDRA+MrCuDQBJtJfS3wKVpbVTv6zOY9PQCX83m3Dvb8PaC8ksWUehMrn8vT7E+3cL3iBG6EIOqhXSGX847jowef97fnsTsWH8yRVx8RIa+7N9UPry4kaZYk+JfE1s7RAdXEWwTZ2q5IAKayf3Q1f60deZacLilZ/rjnKSE+3LgAjmwtvdTRPg/5CaejAoB766qt1pR6NLFkQ3FykAC7+oc9lyzNAsnjC5lXlgxu8ULX3/TILzdbex36VGYBsgLH/D1oxXQv5ERiGHQTYbiBLapO6PLD9Abzeh913zq3w8aRMVXWK/qL1ODPPxiQbqxkgAKQtp8fxqzaVR4Z7ItGQQ2xRRjbtLbXBQVCuqos94zaJmGb6JWCz4WLSBsWDrUU0ibho+ed3kMCj6ULOMaAb06jt3WoO27LIe6XLk91lHKK07nAggMuYxtMZOsf/0PK4wExtg+mfBBuj8Ci0S7gckWv4BfBeri/K+urC9NH8bZ16w60CCaidoUjC8+fvkp3vdGxt5iqpRNd1cAL0fg9ZjknPclL29sIG9s9TFiLRApy7rfshc5BPA8KNVBtBbQkz0jEpFZcWrSEb5PD0vwHq8BJHUXpUD0ETyGYPeQ4/LlL8enBe0/mqt2aCUrqY34+3jEvgjvj1k1q8wMMzUPq5mSreQpxHeDwDC4p4Qa7xnc629LbtAF4vyqFQNsyiwn+sp+VLm3issdU6qu3HQ0MBKflOIervCaw09OP4jFAwHBv6ulp4WM9Z4jIgcey+fLSzOCdV5EMB44YPX2mwiHb09InL7RwNJsKk7AseGNBRxXFWdMK9AgCzb5ZZZ6DWv0dc71jN2xTqjVNGQhA7kOPeDwc75n5bjcpPxTNbqHx9pjI4lXU+Ur8qcO6aDVeQupchyKcyaCTkTdZ6KNYf15TiDN0UDo+7l5YFK1k42Xb+PD8sBwj4qd+om5FIIrEH0rwcHfieFkJ7xwUjTaoZRVxA+Hhm8UojWuknKNJ9rxpS/DE+mWmiLdacfxpkQqpwRihChrgQzKworOBwkvemht2Vd9UCLs9sn6yKAWJO1rUH4U6qptJcDQl7ETBk+5bfjPGZ5gehVY7N2JT3IhjnJwI1EMV0W4UKK2eNeSJaYP39WhfHR0hWa3vXrfWNKZtA2FaEz0t8A6qckTdz0dyOQFEQEVA72drKk1GZwDf6LHzFJlC++7rAtn86T06QKF+bXkC9wSOBzI8HJe/m3zYvO2YfhowR79iQi7cqmRxAOtwObU+OJqsCA7uAWiLUgAj/DGtK2t8uw6ei4pzUVA+U1SQMdKDqCmFfaTG49R3SU4YQV+FZUBW1VE/QevQPajW6Cqo/bNScDAnH1tE88KuIUDO55Ts2nBJAGjZohIeDjZre1aZx/RldlQWJkxcPbGAlBQ17gfjmZEvMpH3DkwanxY31i3m9mrYNV9fUkjPTJM6XatiR2NeGDM/Zm0eQTpfpmsyOTv1soNRgC8el0vi97pnwaInXMI3uDLknFDsBK2grX64vU7eXHT4IEWmfxDZSexHLqkUOKlGkjnkrvDSjlsbYIsjka1tcNEA4YEgroFej7sCLR10TBXy+xM3p8Dnx5SEJDXGT5giQVjW425i0xvpPB9QcIiz7idgiW3/CFsBXKDNPtYv9QnarikI8pxIa1L9SyPS/DlQw2JM911hhxEU9P0yxPx0xypvXsSuIJ/tyLqBDyfig9q8tK/dz+hsdwmjrGehUkjnJqf25cRx0axReE4UsCHdWFvfIppxXzX83dCkLl37o6WRpM0UP6CL8ml+oTnpdrzJtHfnkh/5PgUM6S37/MDF3rwnNAn3VfEGj5w77XSsQuqDOU1bf/HeRQkZc0zyJXl2i+94WE8m24XPUxtug4cvcWOvxxlNoEbP7YsH29zRHC2SGhvHMCDqQt+cbzVv650KssMEvUBD4USXxwnQHuhBAgbqtQCysq9YlMru6YjwsJE+WKH6G5d+8VjewDaaCsJ4+dcjOla4jkEQ18O5pIg556UDu9scZLproP62eG3C/niWMWQZWXKoDvAtBYb0M8wcuUCLs9rZ8nVMXLw9ht0WR0j0U0lZlfJtbQXbPCa9OrzqfvMYEQetUpsrijEiVo77aVMv945pZUYkK3EqYD8WZCEE3EKzizTGpOAXZagrkxR8kB5r4tJtlXyvxA8ED6cERs4Q17Z5hrJgQ/229V3DS1eUM2YghGlW8uTPy60auKrt2YdWmXGV8gXM9aeCfOoQPZwwYU17NPzXJkT1iYUsOGPwPxXWdjWxjxJlyiDmGgm24B4PQv7YxGQv9k1IXvG8Cq5/boVE1KVyVtp57ldztNiYdVG2417NrT2j81virISo+lVonP7JAv5e3b/a98JuJe6++ookxTi4krkg8XIbt4B97R45MbyIXFX1VwFRvLj9iIgbSC1JeumLRqkVyZRgJDcFkH2PryzX4wU5GMMHHG2PUlNtlgjRQPNWyXHs+aJVwfXv8GstaEcnIk/9A5/68+82iX9KE6LO0tsgM8YHV6Oku+k1NevZ8inAeKU3bOpM1EwiPZNlcrGqb+A2/dDSDIid6WetKnDRXXDX4NCXOCCnGcjDUyoHbmujGYczeguMudUA5+6ZhET4Yl2P/NkXMcSYE5/kMmzk1m2QwAVGGTlplQE2Uv9wQQUHrft5sAwXkDj47Q1wsd8noTnrZocJJ/poxcBW98qGzOyVnMYV2YlA0/VojyEw2jkfJEQNYUe3xngTgfvOUcF8JO/+usGyyvvftmgQVjmY4SuMI2Mar4Atpt4LMCzU2PqIkCtRXO2O/VOsXPpdcoHGGw9yuYBfKPfoLa7zTJvmILIfjgiXKPoc74VKYLVaE2DJi6XEdudkU7ltoYKcnAi6x2m7zOUvmPBe0uMPfjZhGttHqcHRsJN2EO97qsMXGx7uiQiBARg4jtCMuEi4ByQ2b3P/uhTEpwIEJVvaJ71rV8xuYKoPmwlGm9vioEM2N+5HvS1mbZnBTNeOGPenUxtsMxgqffwBX8F0DPkTQuum/8oUHostRRnqcMTNhdJuV92sq4/ScJ9XhPHOgfHeQDan/28cl1W/5FXeMXv810Zua37CkPDP6kJga6sV3AdyfgBA6D/muKuUj8BJKuECrm6aevO4z1oPu7N8GXOpqjDciK8ISa7Bb2+jdrQvKcxWjGIPTUH5yszTO+9Y3HNhMzReUbRBWQmbvGuypyZ67GC2Re66JCDPppnrQrCZleGIVbgVT0V0FRzb6N9+c7rkT7n0DE/2h9VjO2ncdnsYYEtLtTG9YUyeex3uLJBk6jRv69kIPWjVFv+zujxE2/nkxlPxW37ykpIHDWToXyOwvjBIXZ62HA0fwgBS9cD7K1n58CneCR9nvq4BcnE7demPlBbhfgsWQwcdzyTXAj1jESMOMhz/lYDUqu69tApgvygJ79L5/19QzOHwyNKSmB9X5mqiFrJeR0WP4dYVtBCQrs9Xv3G9R+ZsAgSADwrWpmE8K2QYbtYrU9nXenjQo59wNy96lL8tlas6DRdvE/rv+lKz7BS8Opy8PHCY7E+WpumGG4zh5LhBZY8mCU/CdCSDHfCj9KqC07Vd1RicgrhNm2fTUhycM45YJT1wTrck7I96HtxoakemlUxcpl6cRaJbLCTSJkVzC27NKgXx0YA7ESHuG2Pq3oSTtpEFkwp2sOFhwQLa1SrHe/VbRoH/Om9vTWK6W9yTAH75aDAT8o8CgvLBFJuho/GNktEo24esdaKxAI6yx4TGKSYQwW7txMazdkcs3CWvoknjZHSfVoy5kmrCxnLAUJHgrb39LjdX+fleRtS8JD2+BOsiSaeOAghoOOMPNXI+BGRRQzneAsOPQxPhoWwqgxrWfS4Z1Lkc9iF00t0fGoxUgdno+LBdXNMUB6OzPfd3HV085wwFWccZ/s9qaKxlIE5+6eJuonpx+xTzMa9rmeRHZmd8xj7gKLHBeKk2YyPphYschgj9+eKBI+9dioRq8Ms8xZXYz5oLe/Eub1wc+yqeHO1ZUxwV0S8IvM+aM4IiziYMXE1oQ2WSLT9cEpqrUm9ih3/NECWP/yNWlQv1PTNN5TYHpJkhpumrpe8tGX3SMH2hd4w08MIPdtJDYAvg+t7+MhX007V4VHogzIMa+itC9xc5SGxvcWggoSuhJpWQX8key/+lOJDLe4fFocPBmqU5M+Va5mg+kp2mm2IfQfnZ7zX3ocYf1CqnxLwIoUWGenHQj+pWkhgjp0jvMiSfenR9a5FROfUuMEYlkmdEgEDFmnf8Kb1hHdwzkDNFqKgf223fqqMYwytBoX84+QbjquFlALidx1R03XSNhSTkiPdvdUTS3lrpQ/p6eKaaGEhtseBMIFWFChJNdYuRZ90jw+55GDqqQR83+wop+RNjMM8S5nefHxOGhKfMUBiNpZf7vuNddUl31Y8+FeaIX6NkRNMRNyH4aAe7RQ3HPf56wL4QU9bcvOrw+y5jqHU6HDwZbI7IWuIns78kydjvIhbXyIjLW7Z0d/1GJPFOQlrOLPR9wx+Y9SYAWA3MVGlFi7K+rnFqe1TXADGs5Q1ja5wf2jh9sYDb3IcUWsR5hRwbdraKxHN9kRPP8SeMiyjiw6teetVpMmnGJ25wPCF33YhCvnWQrM0Hozp9aTNizgF1u0BuR+54tWwka9Hh7UFKqTXeb696Y6RpCZMZD3eMNGnfxnIf/f8GkdF2WQIv0ihGt+AcM/7ZCAT6BYcMRs/IPRAQaT/tyWi9a9PQ8O5wGrOIjOzznuDCFwGRhIe2ec9E0jKYdXKNoBQa/lx81RgGq88b5HaecScq0L6gUVlLCYG5kVaDyVW57Csa+Yae22Uy7ZnNwsLvJAH6yKyKh9mdOK0HBxrhxDyAofylOza8M

**Comment by Nilos** [comment]
We can't decrypt something encrypted with sjcl without the password. Please be more specific in your request for help.
