### ISSUE TITLE
Inclusion of jsdoc toolkit issue

### ISSUE THREAD

**Issue by nikmartin** [bitwiseshiftleft/sjcl#284]
It's a slight bit odd that sjcl includes jsdoc in its own source tree, vs being listed merely as a dependency in a bower.json or package.json file. It bloats the repo pretty heavily to not be a core component . Could this be stripped out or at least swapped for another lighter jsdoc tool? there are several pure js documentation tools that generate docs from javadoc comments.

**Comment by federicobond** [comment]
This is fixed by #292. cc/ @Nilos

**Comment by vladikoff** [comment]
@federicobond @Nilos  This is happening again: 

![image](https://cloud.githubusercontent.com/assets/128755/25868829/1ad098d8-34cc-11e7-8b98-0b5d23fda6a2.png)

```
bower progress      sjcl#1.0.4 Receiving objects:  17% (43/239), 3.29 MiB | 513.00 KiB/s
bower progress      sjcl#1.0.4 Receiving objects:  17% (43/239), 3.86 MiB | 527.00 KiB/s
bower progress      sjcl#1.0.4 Receiving objects:  17% (43/239), 4.48 MiB | 576.00 KiB/s
bower progress      sjcl#1.0.4 Receiving objects:  17% (43/239), 5.14 MiB | 590.00 KiB/s
bower progress      sjcl#1.0.4 Receiving objects:  19% (46/239), 5.14 MiB | 590.00 KiB/s
bower progress      sjcl#1.0.4 Receiving objects:  20% (48/239), 5.14 MiB | 590.00 KiB/s
bower progress      sjcl#1.0.4 Receiving objects:  74% (177/239), 6.14 MiB | 624.00 KiB/s
bower progress      sjcl#1.0.4 Receiving objects:  83% (199/239), 6.86 MiB | 657.00 KiB/s
bower resolved      https://github.com/bitwiseshiftleft/sjcl.git#1.0.4
```

**Comment by nikmartin** [comment]
@vladikoff No, it's now installed as a dev dependency, vs being included in the github repo. What you are seeing is the result of moving jsdoc out of the repo and added ad a dev dependency.
