### ISSUE TITLE
Use of ECDH for message exchange

### ISSUE THREAD

**Issue by thibaut38410** [bitwiseshiftleft/sjcl#285]
Hi, 

I'm new to Javascript and I would need some help for implementing message exchange between two users on a Web-App. 

My question is simple, how would you use SJCL to implement key exchange and message encryption between two users ? 

I came up with this idea : 

User A generates a key pair using `var pair = sjcl.ecc.elGamal.generateKeys(384)` then keeps his private key in HTML Local storage and send his public key to server for storage in DB. 

Then A will use B's public key to generate a shared secret with `secret = secA.dh(pubB) `

Finally A will encrypt a message using AES encryption and the shared secret as key : `enc = sjcl.encrypt(secret, message)`

This encrypted message enc will be stored in DB.

On B's side, B will compute the shared secret with `secret = secB.dh(pubA)`

and then decrypt the message with `sjcl.decrypt(secret, enc)`

What do you think of this solution ? I'm not sure of what to do with the shared secret computed, is it right to use it as a key for AES encryption ? I might be totally wrong, please explain me how can I make it work properly. 

Thanks.

**Comment by Nilos** [comment]
Ja, das dürfte funktionieren.

Man verwendet aber üblicherweise nicht direkt das Diffie-Hellmann Geheimnis sondern leitet von diesem Schlüssel ab. Ansonsten würde man jede Nachricht mit demselben Schlüssel verschlüsseln, was zwar geht, aber nicht immer optimal ist.
