### ISSUE TITLE
Implement DER for ECDSA Signatures

### ISSUE THREAD

**Issue by xcthulhu** [bitwiseshiftleft/sjcl#287]
I cannot verify ECDSA signatures made by SJCL out of the box with alternative cryptography libraries, such as OpenSSL or BouncyCastle.

This is because the signature format used by SJCL does employ [DER Encoding](https://en.wikipedia.org/wiki/X.690#DER_encoding) which is standardly used most libraries (including BitCoin).

In addition, BitCoin attaches an additional bit to their ECDSA signatures so that public keys may be recovered using the technique described here (sometimes called Shamir's trick):

http://crypto.stackexchange.com/a/18106

Here is an implementation of the approach: https://github.com/indutny/elliptic/blob/master/lib/elliptic/ec/index.js#L176

I have recently implemented a modular square root algorithm using SJCL, I may be able to help in implementing the above.

**Comment by Nilos** [comment]
I am happy to merge a Pull Request but do not have the time to implement or help implementing.
Closing this for now!
