### ISSUE TITLE
Increment default PBKDF2 iteration count

### ISSUE THREAD

**Issue by federicobond** [bitwiseshiftleft/sjcl#289]
The current implementation of PBKDF2 uses 1,000 iterations by default. While this made sense in 2010/11 when the library was initially designed, it is no longer considered safe to use such a low value.

My recommendation is to raise the default iteration count to at least 50,000. It is my understanding that `sjcl` aims to provide a simple API so that even people not familiar with cryptography can use strong encryption with secure default parameters, and while it's certainly possible and easy to tweak the iteration count for a particular use case (though unfortunately not documented), it would be responsible to update the defaults.

I would gladly submit a pull request if you are OK with this change.

**Comment by Nilos** [comment]
I would gladly merge such a pull request if it is accompanied with performance metrics in different browsers and on different machines (especially mobile devices!).
1,000 is definitly too low, but we need to find a good tradeoff between speed and security here (leaning towards security as pbkdf2 usually only runs rarely)

**Comment by federicobond** [comment]
Great! I just cobbled together some tests in my laptop and performance is within acceptable range, but could degrade a lot in mobile devices.

Here is what I am going to do:
 * Create a page similar to the one at `browserTest/browserTest.html` for performance metrics
 * Write performance tests for different iteration counts of pbkdf2
 * Test with multiple devices

This should make it easier to do further adjustments to default parameters over the years.
