### ISSUE TITLE
SHA1, SHA256, SHA512 cannot hash more than 256MB of data

### ISSUE THREAD

**Issue by ph4r05** [bitwiseshiftleft/sjcl#299]
None of SHA1, SHA-256, SHA-512 can hash more than 256MB of data. I describe it only for SHA-256 as all of them have the same structure.

The problem is in the `update` function, in particular in setting the initial counter value `i`:

```javascript
for (i = 512+ol & -512; i <= nl; i+= 512)
```

Statement `& -512` is supposed to do integer division on `512+ol` by `512`. Length is computed in bits, as usual. 

The problem is the bitwise operator `&` considers the argument as a 32bit signed integer. Thus `i` can never be greater than `2^31-1`, as `2^31 | 0 = -2^31`. (Just to make it clear, `2^32` bits is 256MB)

As soon as one hashes more than 256MB of data, `i` overflows to negative numbers what leads to incorrect computation (very long/CPU intensive for loop, without throwing an exception).

As SJCL is often used on backends (Node.js), it is a big limitation we can hash only 256MB of data. If SHA256 is used on the server side and user can supply the file to hash this can easily DoS the server.

In JS we can safely compute with integers up to `2^53-1 = 1126 TB` which gives a quite decent margin from the previous 256MB.

I've just submitted a pull request with the fix. The idea is to avoid bitwise operations on the whole length.

```javascript
for (i = 512+ol - ((512+ol) & 511); i <= nl; i+= 512)
```

One could also do

```javascript
for (i = 512+ol - ((512+ol) % 512); i <= nl; i+= 512)
```
But I suppose the former is faster.

**Comment by Nilos** [comment]
Merged your PR.
What I would still like to have:
A test case failing before the PR and being good after the PR (even though this might be hard due to the amount of data involved)
That the library fails for too big inputs. Even though our input margin is now really high, we should still ensure that even if > 1126 TB of data is hashed the library does not simply fail but that it outputs an error.

What do you think?

**Comment by ph4r05** [comment]
Thanks!

I absolutely agree with both things you mentioned. 

I can do the test with 256MB generated (not stored whole in memory) zero vector, if you like. And submit a new PR with it. I will let you know how fast the test is as I have it. 

And I would like if library would rather throw an exception in the case it cannot compute the result ( `sjcl.exception.invalid` ). I can submit another PR with this, if you deem it interesting.

**Comment by Nilos** [comment]
Yes that would be very nice of you! Thanks!

**Comment by ph4r05** [comment]
I've added several pull requests as we discussed. Please review it and merge if it is OK. Thanks!

**Comment by ph4r05** [comment]
Take a look also at #305 
I tried to figure out where is the problem but for now with no success. It would need further investigation.

**Comment by ph4r05** [comment]
Do you think we can close the issue now?

**Comment by Nilos** [comment]
There are no more open issues from my point of view!
