### ISSUE TITLE
sjcl.random mousecollector doesn't require mouse to be moved

### ISSUE THREAD

**Issue by redfish64** [bitwiseshiftleft/sjcl#308]
The sjcl.random._mouseCollector algorithm invoked when calling sjcl.random.startCollector() takes less than 1 second before sjcl.random.isReady() returns non-zero (indicating collection is finished and the pool is ready), even on maximum paranoia level 10 with a 1024 bit seed. This is true even if the mouse is never moved.

I am not an expert in cryptography, but the amount and quality of these measurements seems incongruent with the claim that enough entropy has been generated to create a 1024 bit truly random seed.

**Comment by Nilos** [comment]
That does not seem correct.
First of all, there are more collectors than only the mouse collector (e.g. keyboard, accelerometer and touch). Secondly they only add to the entropy pool if the mouse is moved, so this should not be possible.

Are you sure it is not one of the other collectors, especially the accelerometer collector which provides the entropy in your case? If so, are you sure your mouse is definitely not being moved? Even small movements invisible to you could lead to the effect observed. Finally: can you give more information regarding your test setup? (Browser, Test-Script, etc.)

**Comment by redfish64** [comment]
Sorry, I was wrong. I didn't realize that sjcl.random initializes its pool on startup. It was ready before the collectors started

**Comment by Nilos** [comment]
Yes the entropy pool is initially seeded with crypto.getRandomValues if available. The Collectors were added in a time were crypto.getRandomValues was not available at all.
