### ISSUE TITLE
Very slow for a small dataset

### ISSUE THREAD

**Issue by mmahalwy** [bitwiseshiftleft/sjcl#309]
Using along side with: https://github.com/mdp/gibberish

My data set is very small: 
```
"[[0,630,-1],[630,410,0],[1040,620,1],[1660,950,2],[2610,1720,3],[4330,90,-1]]"
```
Yet it takes around 800ms to decrypt this when encrypted. Any way I can make it faster?

**Comment by Nilos** [comment]
Can you maybe provide the code that you use?

**Comment by mmahalwy** [comment]
```
parsedSegments = JSON.parse(
      decrypt(
        process.env.SEGMENTS_KEY,
        new Buffer(segments, 'base64').toString()
      )
    );
```

**Comment by Nilos** [comment]
`new Buffer(segments, 'base64').toString()` gives `\u0000\u0000\u0000\u0000\u0000\u0000` for me.
This code is on Node, right? Which node version are you using? Why is the function called `decrypt` and not `sjcl.decrypt`?

**Comment by Nilos** [comment]
Or do you input segments as a String?

**Comment by mmahalwy** [comment]
`import { decrypt } from 'sjcl';`

and on node 5.1.1

**Comment by Nilos** [comment]
That syntax is not even supported in node 5.1.1.
Sorry but it feels like I have got to ask for every bit of information. Please provide a full! working example of what you are trying to do that works in node 5.1.1 (including but not limited to: code example, package.json)
