### ISSUE TITLE
Should we hash a password before passing it to sjcl.encrypt?

### ISSUE THREAD

**Issue by rugk** [bitwiseshiftleft/sjcl#313]
Have a look at [this line of code](https://github.com/PrivateBin/PrivateBin/blob/master/js/privatebin.js#L500):
```js
sjcl.encrypt(key + sjcl.codec.hex.fromBits(sjcl.hash.sha256.hash(password)), this.compress(message), options);
``` 

So `key` is just a [randomly generated key](https://github.com/PrivateBin/PrivateBin/blob/master/js/privatebin.js#L996). What matters more to me is `password`, which is user-supplied.
Because do we need to hash the password here or does SJCL already stretch the password internally?
We track this issue in https://github.com/PrivateBin/PrivateBin/issues/74, so there are more information.

You can also have a look on the [general encryption](https://github.com/PrivateBin/PrivateBin/blob/master/js/privatebin.js#L492-L501) algorithm.

If you need to contact us privately, you can find my PGP key as a comment below. (So you need to click on "edit" to see it.)

**Comment by Nilos** [comment]
You do not have to hash the password in this case.
If you call sjcl.encrypt, it will use pbkdf2 to generate a key out of the password provided (in your case key + hex(sha256(password)). You could thus simply concat the key and the password.
You can also take a look in the source code, the corresponding line is here: https://github.com/bitwiseshiftleft/sjcl/blob/master/core/convenience.js#L49
Please remember that this only applies if the password you pass is a string!

**Comment by rugk** [comment]
Okay, so do you recommend this way? May the other way be disadvantageous or even risky?

**Comment by Nilos** [comment]
Both ways should be equally fine as far as I can see it.

**Comment by rugk** [comment]
Is the hashing before passing the password to SCJL useful? Is it bad? Would you recommend it?
(That's actually the question as mentioned in the title.)

**Comment by Nilos** [comment]
I am pretty sure that it does not matter at all. The concatenated password will be put through pbkdf2 which will hash it multiple times anyways. I can see no attack vector in both cases but as everyone knows crypto is hard so no promises :)

**Comment by rugk** [comment]
Soon... what would you suggest?

**Comment by Nilos** [comment]
I would not hash it, as hashing is not necessary. But as you already do hash it in the current version, you can keep it that way, as changing an api might not be worth it.

**Comment by rugk** [comment]
Okay, so I think this issue can be closed.

**Comment by max-l** [comment]
@rugk  the encrypt convenience functions applys pbkdf2 with 1000 iterations:  https://github.com/bitwiseshiftleft/sjcl/blob/master/core/convenience.js#L316

this is low according to this article: https://cryptosense.com/blog/parameter-choice-for-pbkdf2/

It would seem best to not use the convenience function and call pbkdf2 with sufficient iteration count.

Using a single hash function (bcrypt, scrypt or pbkdf2) with a high iteration count is better than combining different functions, see: https://security.stackexchange.com/questions/121272/isnt-using-pbkdf2-scrypt-bcrypt-best
