### ISSUE TITLE
Reducing size of used lib: what are the defaults equivalent (sjcl.json.decrypt/encrypt) with a modular build?

### ISSUE THREAD

**Issue by fabm22** [bitwiseshiftleft/sjcl#314]
Hi,

I'm really not a "crypto" guy so sorry to sound stupid maybe as the answer might seem obvious to some.
Anyway I'm really using the simplest (from a js usage code point view) case of this lib, ie. using the defaults ( I suppose since there is no particular configuration I set anywhere) and using the ```sjcl.encrypt``` and  ```sjcl.decrypt```methods which are *aliases* to ```sjcl.json.encrypt``` & ```sjcl.json.decrypt```

Excerpts from my use:
```var decrypted = JSON.parse(sjcl.decrypt(PASSPHRASE, encrypted));  ```
...
``` $sessionStorage.data = sjcl.encrypt(passphrase, $window.JSON.stringify(data)); ```

Looking to the encrypted data, I fathom the defaults are AES, ccm mode ...
```
{"iv":"lb/2nwowyTXmxGkZUxTz0A==","v":1,"iter":1000,"ks":128,"ts":64,"mode":"ccm","adata":"","cipher":"aes","salt":"jcO7V1j2bks=","ct":"IHhmuoN.... etc.
```
which is coherent with the [source code lines](https://github.com/bitwiseshiftleft/sjcl/blob/master/core/convenience.js#L14)

So my question:

**In order to reduce size of the lib using a custom build what is the way to achieve exactly the same results of the more convenient sjcl.encrypt and .decrypt methods through  more involved usage of the library ??**

I tried for example using those flags for build  config ```./configure --without-all --with-aes --with-convenience ``` my code still works as a charm,   but the convenience flag actually seems to almost add all modules, reducing the size of the build output just fairly.

Is there a way to, maybe, only add --with-aes and --with-ccm (??) and **avoid --with-convenience** and still be able to have same functionality ??? 
Without  the later, the size of the lib is reduced DRASTICALLY. Like divided by four.

Thanks a lot for any help.

**Comment by Nilos** [comment]
Not really. The modules you are missing are: pbkdf2 for password to key transformations. random for random numbers (IVs for ccm) and codecBase64 for base64.
You can see all dependencies here: https://github.com/bitwiseshiftleft/sjcl/blob/master/configure#L33
The default sjcl build only includes the bare minimum already! 25K is also rather small for a crypto library.

**Comment by fabm22** [comment]
Thanks for pointing me out.
