### ISSUE TITLE
"TypeError: Cannot read property 'hex' of undefined" seen after 1.0.5 upgrade

### ISSUE THREAD

**Issue by cmhayes** [bitwiseshiftleft/sjcl#316]
This morning we started seeing "TypeError: Cannot read property 'hex' of undefined" from this line `sjcl.codec.hex.fromBits` . We tried reverting to 1.0.4, but that revert failed with npm, saying the version didn't exist. Finally, reverting to 1.0.3 fixed the issue.

**Comment by isocolsky** [comment]
Getting a similar issue with `sjcl.hash.sha256`.

**Comment by allensanborn** [comment]
I beautified and diffed the 1.0.3 and the 1.0.5 sjcl.js files. The 1.0.3 version has module export near the top:
`"undefined" !== typeof module && module.exports && (module.exports = sjcl);
"function" === typeof define && define([], function () {
    return sjcl
});`
The 1.0.5 version does not contain the module export in the sjcl.js file. It looks like that was moved to an external file "export.js" which would appear to not be part of the bundled code.

**Comment by allensanborn** [comment]
Should the configure file list something like `my %deps = ('sjcl'=>'exports',` ?

**Comment by Nilos** [comment]
Will investigate! Sorry for the inconvenience, for now revert back to 1.0.3 as a workaround.

**Comment by Nilos** [comment]
For some reason the exports was removed from the sources list. I re-added it and released version 1.0.6 as a fix.

**Comment by Nilos** [comment]
Npm is messing with me and breaking my internet connection, just a little more wait time ..

**Comment by Nilos** [comment]
The new version has been published! Hope all is well now!

**Comment by willdurand** [comment]
Awesome, thank you ❤️

**Comment by Nilos** [comment]
I am still not sure though what exactly caused the problem. exports.js was automatically re-added when I ran ./configure --compress=closure

**Comment by neojack647** [comment]
I do not believe this fixed the issue. I pulled from master and I am still getting the same error.

**Comment by neojack647** [comment]
this is an issue with how amgular-cli is loading 3rd party dependencies not with SJCL
