### ISSUE TITLE
Unable to rebuild from npm

### ISSUE THREAD

**Issue by carldunham** [bitwiseshiftleft/sjcl#319]
In 1.0.3 and prior, we would include

```
  "scripts": {
    "postinstall": "cd node_modules/sjcl && ./configure --with-ecc && make sjcl.js",
  }
```

in `package.json` files that required ecc (or other re-configs). Now in 1.0.6 this fails because the `compress` directory is no longer included, but still referred to by the Makefile.

**Comment by Kerumen** [comment]
Hello?

It's impossible to rebuild this 3k+ stars module since 3 months..

**Comment by Kerumen** [comment]
@Nilos Thanks for the clarification :)

**Comment by Nilos** [comment]
Sorry I responded to this issue so slowly :)
Hope this is okay now for @carldunham

**Comment by 7freaks-otte** [comment]
Years later, just in case someone needs to do this as well.
I was able to "force" `compress/compiler.jar` to be included by installing sjcl via the tarball url:

```npm install https://github.com/bitwiseshiftleft/sjcl/tarball/master```
