### ISSUE TITLE
How to decrypt the sjcl.encrypt-data in the PHP backend?

### ISSUE THREAD

**Issue by Amamatthew** [bitwiseshiftleft/sjcl#321]
`<pre>
  <form id="frm1" action="form_action.asp">
    Firstname: <input type="text" name="fname" id="fname">
    Lastname: <input type="text" name="lname" id="lname"><br>
    Password: <input type="text" name="pwd" id="pwd"><br>
    <input type="button" value="Submit" id="btnAjaxSubmit">
  </form>
</pre>`
`<pre>

$(document).ready(function () {
    $("#btnAjaxSubmit").click(function () {
      //Get params
      var fname = $("#fname").val();
      var lname = $("#lname").val();
      var pwd   = $("#pwd").val();
      var ori_param  = 'fname=' + fname;
          ori_param += '&lname=' + lname;
          ori_param += '&pwd=' +pwd;
      var encry_str  = sjcl.encrypt("Encry_key", ori_param);
      var encry_data = 'data=' + encry_str;
      //Post Request
      var options = {
          url: 'async_submit_test1.php?action=SaveUserInfo',
          type: 'post',
          dataType: 'text',
          data: encry_data,
          success: function (data) {
              if (data.length > 0)
                  $("#responseText").text(data);
          }
      };
      $.ajax(options);
      return false;
   });
  });
</pre>`

**Comment by Nilos** [comment]
You should be able to decrypt sjcl encrypted content with standard crypto Libraries in your PHP backend.
SJCL uses AES in Counter with CBC-MAC mode.
I can not give you an example though, you will have to solve this on your own.

**Comment by robocoder** [comment]
There is now a php 7.1.0 example in http://stackoverflow.com/a/41323920/1644312
