### ISSUE TITLE
Generate sjcl.ecc.ecdsa public key from a pre-existing secret?

### ISSUE THREAD

**Issue by CrackerHax** [bitwiseshiftleft/sjcl#322]
Hi, I am trying figure out how to generate a public secp256k1 key from a pre-existing secret such as:

    var secret = sjcl.codec.hex.fromBits(sjcl.hash.sha256.hash("ThisIsMySecret"));

Is there any way to do this with sjcl?

**Comment by CrackerHax** [comment]
Anybody?

**Comment by Bren2010** [comment]
I haven't worked on sjcl in a long time, but it's probably not possible without hacking something out. Even if you [seed the generator deterministically](https://github.com/bitwiseshiftleft/sjcl/wiki/Symmetric-Crypto#seeding-the-generator), sjcl tries to pull in high-quality unseeded randomness [from the runtime](https://github.com/bitwiseshiftleft/sjcl/blob/master/core/random.js#L495).

**Comment by Nilos** [comment]
I agree with @Bren2010 here. You could also try to create a big number out of the pre-existing secret but I am unsure of how much can be done there because big numbers need to adhere to a certain format
