### ISSUE TITLE
Unable to import to React Native

### ISSUE THREAD

**Issue by baobabKoodaa** [bitwiseshiftleft/sjcl#323]
I installed sjcl via npm according to the instructions on RN docs:

```
npm install sjcl --save
react-native link
```

Then I tried various ways of importing the library to my RN project, for example:

`import sjcl from 'sjcl';`

Looks like this doesn't import everything in the sjcl node package, it only imports file sjcl.js from node_modules/sjcl/. I also need sha1.js from node_modules/sjcl/core/sha1.js. I've tried various ways of importing it, but nothing works.

**Comment by TheTaylorHicks** [comment]
Hey @baobabKoodaa,

Have you tried cloning a recompiling SJCL with the --with-all flag?

    git clone https://github.com/bitwiseshiftleft/sjcl.git
    cd sjcl
    ./configure --with-all
    make

After running those commands, you should be able to take the new sjcl.js file and add it to your project directly.

**Comment by baobabKoodaa** [comment]
Hey, thanks for your help. Sounds like that would probably do it, but I'm not working on that particular project anymore.
