### ISSUE TITLE
refactor /demo/example.js

### ISSUE THREAD

**Issue by Visgean** [bitwiseshiftleft/sjcl#324]
As an example it works by show casing what can be done with the library, but the demo code is unreadable: 
- what the hell is ``v`` object? 
- what is ``rp`` object?

More importantly the functions as decrypt / encrypt should be *pure* - they should work only with arguments they receive and leave the global objects alone. That way developers can actually see what data is necessary for decrypting and encrypting.

**Comment by Nilos** [comment]
I agree with that `v` and `rp` are not the best of names, `formData` would be a better name for `v` and `resultMeta` would be a better name for `rp`.

I do not really understand why you think decrypt / encrypt should be pure functions. The only thing they do require in the global state is the random number generator (as far as I know) so please describe in more detail what global objects you mean. Or are you talking about doDecrypt/doEncrypt and not sjcl.decrypt/sjcl.encrypt. Please go into more detail what you mean here!
