### ISSUE TITLE
Hashed password truncated to 4 bits?

### ISSUE THREAD

**Issue by robocoder** [bitwiseshiftleft/sjcl#325]
When using aes-128-ccm, "ks" is 128. However, there are 4 places in  `https://github.com/bitwiseshiftleft/sjcl/blob/master/core/convenience.js`
where the hashed password is truncated to 4 bits (given that password is a bitarray, and 128/32 = 4), e.g.,
```
tmp = sjcl.misc.cachedPbkdf2(password, p);
password = tmp.key.slice(0,p.ks/32);
```

Shouldn't that be `password = tmp.key.slice(0,p.ks);` (128 bits) or perhaps, `password = tmp.key.slice(0,p.ks/4);` (32 bits) instead?

**Comment by Nilos** [comment]
This is actually correct as one array element encodes a 32-bit word. (It is not an *actual* bitarray).

See also: 
https://github.com/bitwiseshiftleft/sjcl/blob/master/core/bitArray.js#L17
