### ISSUE TITLE
pbkdf2 oddity

### ISSUE THREAD

**Issue by robocoder** [bitwiseshiftleft/sjcl#326]
sjcl: 1.0.6 (minified)
node: v5.2.0

Passing bitarrays to pbkdf2:
```
var sjcl = require('./sjcl');
console.log(sjcl.codec.base64.fromBits(sjcl.misc.pbkdf2(sjcl.codec.utf8String.toBits('password'), sjcl.codec.utf8String.toBits('salt'), 1000)));
```
returns the expected "YywoEuRtRgQQK6dhjp1tfS+BKPYma0oDJk0qBGC33LM=".

But passing strings to pbkdf2:
```
var sjcl = require('./sjcl');
console.log(sjcl.codec.base64.fromBits(sjcl.misc.pbkdf2('password', 'salt', 1000)));
```
unexpectedly returns "oJfeg8eWRpTFHERHMrKjceXd6lkj7MrymrzUSUafi98=".

It appears to be a problem with the minified code when the salt is passed as a string. It works correctly with the unminified code.

**Comment by robocoder** [comment]
Nevermind... I'll update my code to use https://github.com/bitwiseshiftleft/sjcl/blob/master/sjcl.js

**Comment by robocoder** [comment]
For the record, I was using https://cdnjs.cloudflare.com/ajax/libs/sjcl/1.0.6/sjcl.min.js -- evidently, it's a bad build.

**Comment by robocoder** [comment]
ping @x09326

**Comment by Nilos** [comment]
I could not reproduce your problem on my machine. I always get the same result for both operations, using either the npm version of sjcl or the downloaded sjcl.min.js.

**Comment by robocoder** [comment]
Mea culpa. I mixed up the versions I downloaded. The faulty build was actually from http://bitwiseshiftleft.github.io/sjcl/sjcl.js
