### ISSUE TITLE
Problem triying to decrypt on c++

### ISSUE THREAD

**Issue by animalillo** [bitwiseshiftleft/sjcl#331]
We've set up a nice password manager for nexcloud using this library in the core of the cryptography, but now I was trying to create an android application, and using c++ to decrypt a everything using openssl.

I've been struggling for a while trying to decrypt an string encrypted by sjcl with no luck. So maybe you guys could point to me what am I missing or what have I misunderstood.

What i think is going wrong is the pbkdf2 key derivation as sjcl returns something different than openssl while giving the same parameters.

If i'm not wrong from what i seen in the sjcl library pbkdf2 uses sha256 hashing, so that's what i've set up in my code.

with SJCL i get the following result:
> sjcl.codec.base64.fromBits(sjcl.misc.pbkdf2("test", "X6euCSyszjI", 1000, 256))
> "T4noxNqO3V8GhsFY6N4zEFuD1tlBY5VbPn76DelEFB4="

But on my code in c++ i get: (at line [125](https://gist.github.com/animalillo/be76e5bee32847d1759d879b0c4ac560#file-passman-lib-cpp-L125))
> GRkHuppAjShRzQ+mjC8mTsiSTQ1v9k/IWAcO47d7JVI=

the function where everything (included the output JSON returned by SJCL) is **test()**

The code can be found on this [gist](https://gist.github.com/animalillo/be76e5bee32847d1759d879b0c4ac560)

**Comment by animalillo** [comment]
nvm, figured it out

**Comment by Nilos** [comment]
If you have the time later on, you could add your findings too https://github.com/bitwiseshiftleft/sjcl/wiki/In-Other-Languages
