### ISSUE TITLE
uses of randomWords in convenience.js use 0 paranoia

### ISSUE THREAD

**Issue by animalillo** [bitwiseshiftleft/sjcl#333]
The uses of randomWords in the convenience functions use a hard-coded paranoia level of 0 instead of the one set by default globally, is this intentional? Am i missing something?
Example of such use: [here](https://github.com/bitwiseshiftleft/sjcl/blob/master/core/convenience.js#L28)
As here is said, a paranoia of 0 is not secure: [here](https://github.com/bitwiseshiftleft/sjcl/blob/master/core/random.js#L109)

**Comment by Nilos** [comment]
This is totally fine as this is only for IV generation.
An IV has to only be unique. It is not required that it is actually cryptographically random.

**Comment by animalillo** [comment]
is it also ok for [salts](https://github.com/bitwiseshiftleft/sjcl/blob/master/core/convenience.js#L321)?
