### ISSUE TITLE
codec for base-10 integer strings?

### ISSUE THREAD

**Issue by petertorelli** [bitwiseshiftleft/sjcl#341]
Hello,

I see codecs for creating bitArrays from hex strings, utf8Strings, and a variety of other formats, but none for base-10 integer strings. Is it in there under another namespace? If not, would it be a useful addition? I'd make a pull request.

Thanks,
Peter

**Comment by Nilos** [comment]
If it is useful to you you can add it. It will not be included in the default build though.
