### ISSUE TITLE
Hosted version of sjcl.js with ECC included

### ISSUE THREAD

**Issue by marncz** [bitwiseshiftleft/sjcl#343]
Hi all, I am developing a Drupal module and I am using SJCL library with ECC, I have built the library with --with-ecc option, but I would like to find this version of SJCL hosted somewhere available for users to download.

My question is: can I find sjcl-ecc.js hosted somewhere? is it possible to include that file in this repo?

**Comment by Nilos** [comment]
I don't know if you can find sjcl-ecc.js hosted somewhere, we do not host it. We are also against adding custom-builds to the repo.
