### ISSUE TITLE
New Android system webview cause crash

### ISSUE THREAD

**Issue by shunxingchen** [bitwiseshiftleft/sjcl#424]
Latest Android system webview version: 89.0.4389.105 could crash some Android apps that using sjcl JS lib. Could you please check if solution!!!

Same case happened about 4 years ago.

Thanks!

**Comment by ogryb** [comment]
There is nothing this library can do about it. Google has fixed WebView already: https://stackoverflow.com/questions/66757860/how-to-troubleshoot-crash-in-app-running-android-11-sdk-30

**Comment by shunxingchen** [comment]
Yes you are right, this time no need sjcl lib change
