### ISSUE TITLE
ccm: tag doesn't match

### ISSUE THREAD

**Issue by tirabc** [bitwiseshiftleft/sjcl#53]
Hi all,
I'm a sjcl lib newbie and i tried to implement your great lib in my own app.

This is my console log when trying to decrypt a cipher text:
info: {"iv":"dF WOrTZuP1jyrG3nQShog","v":1,"iter":1000,"ks":128,"ts":64,"mode":"ccm","adata":"",
"cipher":"aes","salt":"O0kTE3nPq2E","ct":"ZoI8uDoN4oucEXXp2Q"}
error: An exception occurred.
Traceback (most recent call last):
CORRUPT: ccm: tag doesn't match

I don't know how to fix this error. Could you help me please ?

**Comment by TheNilesh** [comment]
Issue is with character encoding, I guess.

**Comment by tylerlevine** [comment]
@Nilos Was this bug reintroduced by https://github.com/bitwiseshiftleft/sjcl/commit/abad033b9c868d37e540ebf01ac918c7644b132a?

**Comment by dioptre** [comment]
This breaks also in react-native in "release" mode once it's compiled for the appstore. :( Would be great to understand why this breaks esp as it works in debug mode. The alleged fix above does not work for react-native. Anyone got this to work on react-native? I've started a fork that attempts to get it ready: https://github.com/dioptre/sjcl
