### ISSUE TITLE
Interest in adding RSA support?

### ISSUE THREAD

**Issue by evanj** [bitwiseshiftleft/sjcl#82]
Since SJCL now includes ECC public/private key operations, would there be any interest in adding RSA? It seems like Tom Wu's JSBN is the "typical" implementation used by most JS libraries, and is released under a relatively friendly BSD licence:

http://www-cs-students.stanford.edu/~tjw/jsbn/

I'm asking because I need RSA operations to be compatible with Google Keyczar, so I'm either going to use Forge, or cobble together my own RSA implementation to use with SJCL :( If there is interest, I'd love to help get it integrated.

**Comment by polkovnikov-ph** [comment]
RSA is still one of the most required things in JS cryptography, and we still need it.

Maybe someone opts to make a pull request. Reopen it, please.
