### ISSUE TITLE
Results don't match up with manually inputted Koblitz curve

### ISSUE THREAD

**Issue by vbuterin** [bitwiseshiftleft/sjcl#86]
I'm trying to use sjcl with the secp256k1 Koblitz curve:

```
field = sjcl.bn.pseudoMersennePrime(256, [[0,-1],[4,-1],[6,-1],[7,-1],[8,-1],[9,-1],[32,-1]])
diff = "0x14551231950b75fc4402da1722fc9baee"
x = "0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
y = "0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8"
c = new sjcl.ecc.curve(field,diff,0,7,x,y)
c.G.mult(2).x.toString()
> "0x3818704452a03d52f1ccc4276e45d4a6f70113ae41ae89678517b39616c3ae30"
```

However, the result I get doesn't match up with any other ECC implementation (there are lots of them since secp256k1 is "the Bitcoin curve"). For example, putting:

```
0000000000000000000000000000000000000000000000000000000000000002
```

as the secret exponent into http://brainwallet.org gives:

```
04c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee51ae168fea63dc339a3c58419466ceaeef7f632653266d0e1236431a950cfe52a
```

and my own hand-made implementation confirms this. Even running point doubling manually in sjcl gives the same result:

```
m = c.G.x.mul(c.G.x).mul(3).mul(c.G.y.mul(2).inverse())
m.mul(m).sub(c.G.x.mul(2)).toString()
> "0xc6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5"
```

So why does the library give me 0x3818? Is it a bug, am I misstating the curve parameters in some weird way that only applies for point multiplication and not the manual field operations?

**Comment by Arti2102** [comment]
field = sjcl.bn.pseudoMersennePrime(256, [[0,-1],[4,-1],[6,-1],[7,-1],[8,-1],[9,-1],[32,-1]])
diff = "0x14551231950b75fc4402da1722fc9baee"
x = "0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
y = "0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8"
c = new sjcl.ecc.curve(field,diff,0,7,x,y)
c.G.mult(2).x.toString()
> "0x3818704452a03d52f1ccc4276e45d4a6f70113ae41ae89678517b39616c3ae30"

**Comment by Arti2102** [comment]
field = sjcl.bn.pseudoMersennePrime(256, [[0,-1],[4,-1],[6,-1],[7,-1],[8,-1],[9,-1],[32,-1]])
diff = "0x14551231950b75fc4402da1722fc9baee"
x = "0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"
y = "0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8"
c = new sjcl.ecc.curve(field,diff,0,7,x,y)
c.G.mult(2).x.toString()
